cross-seed/cross-seed

src/cache.js
src/cmd.js
src/decide.js
src/index.js
src/preFilter.js
src/runtimeConfig.js
src/utils.js

Not sure if this is what you had in mind for how to approach the timestamp filtering, but I thought I would take a stab at it.

Store first and last search time and add filter options

---

src/jackett.js

Right now it replaces just the first one

Replace all dots in name

---

src/constants.js
src/jackett.js

Currently for files named like TITLE.2020.1080p cross-seed would search TITLE 2020 1080, not finding anything on most trackers. This PR fixes it.
See: https://regex101.com/r/xgUoGs/1/

Fix movies regex

---

.idea/dictionaries/mmgoodnow.xml
.idea/modules.xml
Dockerfile
README.md
package-lock.json
package.json
src/clients/rtorrent.js
src/cmd.js
src/config.template.docker.js
src/config.template.js
src/constants.js
src/errors.js
src/index.js
src/jackett.js
src/logger.js
src/runtimeConfig.js
src/server.js
src/startup.js
src/torrent.js
src/utils.js

Direct client integration

---

src/constants.ts
src/db.ts
src/decide.ts
src/logger.ts
src/pipeline.ts
src/searchee.ts
src/torrent.ts

Daemon perf

---

src/clients/RTorrent.ts
src/searchee.ts

[rtorrent] Check for download completeness

---

.idea/dictionaries/mmgoodnow.xml
package-lock.json
src/cmd.ts
src/config.template.docker.js
src/config.template.js
src/configuration.ts
src/pipeline.ts
src/pushNotifier.ts
src/runtimeConfig.ts
src/server.ts

Add support for push notifications

---

src/clients/RTorrent.ts

Fix [object Object] logs

---

package-lock.json
package.json
src/logger.ts

Add log rotation

---

src/cmd.ts
src/decide.ts
src/diff.ts
src/searchee.ts

Add diff tool

---

.idea/dictionaries/mmgoodnow.xml
src/pipeline.ts
src/startup.ts
src/torznab.ts
src/utils.ts

Search by season and ep

---

.idea/dictionaries/mmgoodnow.xml
package-lock.json
package.json
src/clients/QBittorrent.ts
src/cmd.ts
src/pipeline.ts
src/runtimeConfig.ts
src/searchee.ts
src/torrent.ts

Hopefully fixes #74, fixes #144 
Please test. Docker tag `qbittorrent` or clone the repo, check out the `qbittorrent` branch, `npm link && npm link cross-seed`

Fix qBittorrent injection edge cases

---

src/decide.ts
src/jackett.ts
src/pipeline.ts
src/server.ts
src/torznab.ts

Closes #204 
```http
POST /api/announce
Content-Type: application/json
{
"name": "string", // torrent name
"guid": "string", // ideally the torrent's comments/listing url, would be for caching purposes
"link": "string", // download link
"size": "number", // in bytes
"tracker": "string" // this is for logging purposes
}
```

Add announce API

---

src/cmd.ts
src/config.template.cjs
src/config.template.docker.cjs
src/configuration.ts
src/runtimeConfig.ts
src/server.ts

Support custom ports

---

src/torrent.ts

Parse torrents in torrentDir one at a time

---

README.md

https://github.com/JohnDoee/autotorrent/ has been archived

autotorrent -> autotorrent2

---

.idea/cross-seed.iml
src/action.ts
src/constants.ts
src/pipeline.ts
src/pushNotifier.ts

Only notify on action taken

---

package-lock.json
package.json
src/cmd.ts
src/pipeline.ts
src/torrent.ts

Fixes #241. Fuzzy searching is inherently messy so this won't really ever have 100% efficacy. We can tune the parameters based on how well we think it's working.

Implement primitive fuzzy search

---

src/constants.ts
src/pushNotifier.ts
website/docs/reference/options.md

This helps integrators such as Notifiarr assemble their own UIs out of the data. 
@austinwbest

Add raw data to notification payload

---

src/torznab.ts

stop double-encoding torznab query params

---

src/cmd.ts
src/configuration.ts

Fix docker config autogen

---

src/clients/QBittorrent.ts

Fix qBittorrent login

---

src/clients/QBittorrent.ts
src/logger.ts
src/torrent.ts

Warn on no save path

---

src/cmd.ts
src/jobs.ts
src/migrations/02-timestamps.ts
src/migrations/migrations.ts
src/pipeline.ts
src/preFilter.ts
src/torrent.ts
src/torznab.ts

Per indexer timestamps

---

src/pipeline.ts
src/preFilter.ts

There's a bug where people are seeing `Searching 0 indexers for …` logs for every torrent in their list. My guess is that this is because the timestamp prefiltering is using different rules for including indexers in the calculations than the individual timestamp calculations in the main loop. This changes the prefiltering to use the same `getEnabledIndexers()` method for including indexers. 
fixes #431

filter indexers the same way in both situations

---

src/cmd.ts
src/torznab.ts

should help out with #354. you still will need to fix the root cause but at least won't need to nuke your cross-seed DB.

Recheck indexers without search caps

---

package-lock.json
package.json
roundtrip.mjs
src/action.ts
src/clients/QBittorrent.ts
src/clients/RTorrent.ts
src/clients/TorrentClient.ts
src/clients/Transmission.ts
src/cmd.ts
src/configuration.ts
src/decide.ts
src/index.d.ts
src/parseTorrent.ts
src/searchee.ts
src/torrent.ts
src/utils.ts

remove dependency on parse-torrent

---

src/torznab.ts

Respect `Retry-After` header in Torznab queries

---

src/config.template.cjs
src/config.template.docker.cjs
src/pushNotifier.ts

Reverts cross-seed/cross-seed#456

Revert "feat(notifier): add support for basic auth"

---

src/Result.ts
src/clients/QBittorrent.ts
src/clients/RTorrent.ts
src/clients/Transmission.ts
src/utils.ts

Add universal url-with-credentials parser

---

src/pushNotifier.ts

Added an `event: "TEST"` in `extra` object to the JSON for test-notification (`sendTestNotification()`) 
It should not affect other apprise integrations.

fix(notification): added event object to test-notification

---

src/pipeline.ts
src/server.ts

feat: announce - return a 202 on torrent not completed

---

src/pipeline.ts

This changes the logic of `findOnOtherSites` to ensure that the search is considered as "complete" only when the torrent itself is complete.
This avoids issues where the torrent is not complete yet the search is marked as successful therefore there won't be a search done for the torrent once it has completed.

findOnOtherSites only completes if the torrent is complete

---

src/clients/Deluge.ts

this addresses when the web_ui is not connected to a daemon.
it will get the available daemons and connect to it
the current implementation, if not connected, will return errors or empty json results.

fix(deluge/webui_unconnected): checks for webui being connected to daemon

---

src/auth.ts
src/cmd.ts
src/config.template.cjs
src/config.template.docker.cjs
src/configSchema.ts
src/configuration.ts
src/runtimeConfig.ts

removes option to configure apiauth in daemon/config files

feat(force-apiauth): removes optional apiAuth

---

src/pushNotifier.ts

This PR adds logging details to pushNotifier.ts for status code and errors given when notifications are sent.

add(logging/pushnotifier): adds status code and error to logging

---

src/config.template.cjs
src/config.template.docker.cjs

update(config-tempates): adds v6 options and organizes the config

---

src/action.ts
src/clients/Deluge.ts
src/clients/QBittorrent.ts
src/clients/RTorrent.ts
src/clients/TorrentClient.ts
src/clients/Transmission.ts
src/cmd.ts
src/configSchema.ts
src/configuration.ts
src/decide.ts
src/logger.ts
src/pipeline.ts
src/runtimeConfig.ts
src/searchee.ts
src/startup.ts

adds functionality to link data-based searches to tracker-specific subdirectories inside of linkDir
fixes nested data not linking to single file torrents
adds torrent backed linking support
potentially close #400

feat(linking): new linking structure and torrent-backed linking

---

src/action.ts
src/configSchema.ts
src/pipeline.ts
src/runtimeConfig.ts
src/startup.ts
src/torrent.ts

This PR makes torrentDir nullable, and adds support for non-linked perfect matches when using data based matching.

feat(matching): feature parity for torrent/data matching

---

src/clients/QBittorrent.ts

this fixes the case when path is truthy (linked) and the searchee is torrent backed
because we only check for path before setting category to eliminate autotmm problems by using only one category, the category for linking is set to linkCategory.
if the searchee is torrent-backed, we should be tagging from the category of the searchee, not the destination category of the candidate.

fix(clients/qbit): yet another qbit PR to fix tagging

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Addresses capitalization in issue templates

chore(issue-templates): update capitalization

---

Dockerfile

Also disabled npm update and fund logs

ci(npm): remove warn for cleanup dev deps

---

src/clients/QBittorrent.ts

needed parenthesis around the NOT operator in skip_checking formData

fix(qbit/skiprecheck): not logic operator not applied properly

---

src/clients/QBittorrent.ts

1. Properly checks if `.cross-seed` exists
2. Will not add `.cross-seed` to linkCategory

bug(qbit): fix tagging with duplicateCategories

---

src/decide.ts

fixes incorrect comparisons of match for repack/proper regex

fix(decide): release version incorrectly compared

---

src/clients/Deluge.ts

this accepts paused torrents if either marked with progress 100% or no remaining download, as well as adds total_remaining to the acceptable completion indicators
this may not entirely solve #711 but may increase likelihood that it is not show-stopping

update(client/deluge): broaden indicators determining completion in client

---

src/constants.ts

bug(regex/group): fix last character of group being removed in some cases

---

src/clients/QBittorrent.ts

With lots of torrents, qbit can sometimes be slow to respond. 3s should catch pretty much all cases but added a failsafe.

enhancement(clients/qbit): better handling of post-injection verification

---

src/clients/QBittorrent.ts

Using `savePath` and `downloadPath` is now correctly applied if `!autoTMM`. Previously this was `path` which would be incorrect if the user is not linking and does not have autoTMM.
autoTMM would not be enabled if the user had flatLinking false but was not linking. If autoTMM is ever true that means we are not linking and the original torrent has it, so we can just use the value directly.
Refactored how tagging is handled so the logic is much simpler. The state of `searcheeInfo` is all we need.
We will now actually duplicate the category if we are not linking. This preserves old v5 behavior so cross seeds don't show up in arr categories. If it was linked, will will use tags as we have in v6.
The new logic was simplified by relying on what the state could be based on `searcheeInfo` being …

fix(qbit/inject): better handling of autoTMM and duplicate cats for injection

---

.github/ISSUE_TEMPLATE/bug_report.yml
src/config.template.cjs

this PR clarifies the new restrictions implemented in the config validation and explains the ratio relationship between time-based values

update(config/template): descriptions for time-based options

---

src/action.ts

Users of `linkType: "symlink"` may have gotten themselves into a situation where they have the following, due to cross-seed picking different "representative searchees" of a group of matches over time. 
```
symlink A -> symlink B -> original
```
It is then confusing and hard to manage the files when they want to delete symlink B - even though the original still exists, symlink A is broken. 
This PR adds logic to resolve symlinks to the original file to prevent this. It's more similar to hardlinking behavior, except the original still can't be deleted.

fix(action/linking): resolve symlinks prior to linking

---

src/clients/Deluge.ts
src/clients/QBittorrent.ts
src/decide.ts
src/searchee.ts
src/server.ts
src/utils.ts

Also will now log the original title when source from torrent as `Title S7 [Season 7 [adfedfe7...]]`.
Now sanitizing infoHash in logs.

fix(searchee): use parsed titles for searchees

---

.github/workflows/ci.yml
.gitignore
package-lock.json
package.json
tests/constants.test.ts
tests/factories/file.ts
tests/factories/searchee.ts
tests/utils.test.ts

This is for a conversation I'm having with Zakary - can be ignored for now (:

[EXAMPLE] Adds test framework via `vitest`

---

src/inject.ts

Since all searchees are checked, a user will pretty much always have the blocklist message if no match and anything blocklisted.

fix(inject): false positive blocklist message summary

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

update(issue-template): change ordering of templates to reduce confusion

---

.idea/dictionaries/zak.xml
src/action.ts
src/arr.ts
src/clients/Deluge.ts
src/clients/QBittorrent.ts
src/clients/RTorrent.ts
src/clients/TorrentClient.ts
src/clients/Transmission.ts
src/config.template.cjs
src/configSchema.ts
src/configuration.ts
src/constants.ts
src/dataFiles.ts
src/db.ts
src/decide.ts
src/diff.ts
src/errors.ts
src/jobs.ts
src/logger.ts
src/migrations/00-initialSchema.ts
src/migrations/05-caps.ts
src/parseTorrent.ts
src/preFilter.ts
src/pushNotifier.ts
src/searchee.ts
src/server.ts
src/startup.ts
src/utils.ts

final pass for jsdoc and spell-check and basic ide warnings for stable release v6

cleanup(prep/v6-stable): spell-check and formatting for v6 stable

---

src/cmd.ts
src/inject.ts

If a user has lost their client session information, `cross-seed` is often used to regain their torrents using data based searching. While that will still be necessary to be complete, we can use `torrent_cache` to aide this processess. The `torrent_cache` will likely also contain the "original" torrents, not just cross seeds, as we only know if a torrent already exists after snatching.
With `cross-seed restore`, torrents from `torrent_cache` are copied to `outputDir` in the naming format. Users would then run `cross-seed inject` with dataDirs to complete the restore.
Copying is done so the cache is not modified and it also allows for `cross-seed` to be restarted during the injection process. Injected or unmatched files will get cleaned up naturally by the job. They also retain the …

feat(restore): add `cross-seed restore` to inject torrents from cache

---

src/constants.ts
src/server.ts
src/utils.ts

Example:
```
2024-10-27 16:12:24 error: [announce] Missing required params: {guid, link} in {
name: 'ABC',
gui: 'https://XYZ.com/torrent/download/3112917.[REDACTED]',
lin: 'https://XYZ.com/torrent/download/3112917.[REDACTED]',
tracker: 'XYZ'
}
```

enhancement(announce): specify missing parameters

---

.idea/vcs.xml
src/server.ts

Per me and @zakkarry comments in #828

feat: add simple /api/ping endpoint

---

src/searchee.ts

fix(searchee): handle errors when creating data based searchees

---

src/action.ts
src/cmd.ts
src/configSchema.ts

since `seasonFromEpisodes` defaults to 1 - there is not any way to use cli to disable it.
this adds `--no-season-from-episodes`
documentation has been updated for this

update(cli/ensemble): add cli arg --no-season-from-episodes

---

src/configSchema.ts

This prevents users from using types that their config does not support.

enhancement(config/blockList): prevent useless blockList entries

---

src/clients/RTorrent.ts

fix(rtorrent): get correct save path for ensemble

---

src/cmd.ts

Knex requires `.destroy()` to be called if the database was used. The change discussed [here](https://github.com/cross-seed/cross-seed/pull/857#discussion_r1899281648) means memDB always has the schema created on startup, and thus needs to be destroyed for all `cross-seed cmd`.
`destroy()` seems to have no effects so calling both everywhere is best.

fix(db): prevent cross-seed hanging on exit

---

src/clients/TorrentClient.ts

This now takes into account `includeSingleEpisodes` and `includeNonVideos`.
`Label.Search` is used as the label as this best represents the tests we need to perform. We don't need to worry about the `.path` based tests since these are torrent based.

fix(linking/test): use filterByContent instead of only blockList

---

src/parseTorrent.ts

See https://github.com/cross-seed/cross-seed/issues/879

Ignore malformed or empty announce-list field

---

src/torrent.ts

The refactor of `cacheEnsembleEntry` in #857 was missing `await`. New torrents added to the client after cross-seed startup wasn't being added to the db for ensemble.

fix(indexing): properly index new ensemble entries

---

src/startup.ts

Fixes #731
Will retry startup connections every minute for 5 minutes. `Promise.all` seemed to cause the others to fail if any does so `Promise.allSettled` is used.
It will not retry indefinitely as existing users may depend on the container exiting on errors. 5 minutes should cover any transient errors.
We also can't ignore any of these errors as many aspects of startup relies on them.

fix(startup): delayed retries for checks on startup

---

src/cmd.ts
src/config.template.cjs
src/configSchema.ts
src/configuration.ts
src/pushNotifier.ts
src/runtimeConfig.ts

Fixes #884
Had to use `createCommandWithSharedOptions` for `cross-seed test-notification` since we are doing config validation now.

enhancement(pushNotifier): support multiple urls

---

src/cmd.ts

#896 refactored the startup but didn't remove this import

fix(import): remove signalHandlers.js

---

src/cmd.ts
src/diff.ts

Options such as `searchCadence` should only defined in daemon mode, so that `cross-seed search --no-exclude...` doesn't require setting `searchCadence: null` in the config before hand.
I also updated the `cross-seed diff` command to only show the files. Since this command is to see why two torrents are not a match, `name` and `length` are distracting. If the user wants to see the these, they can use `cross-seed tree` separately (which also displays the parsed title). The files are also sorted in different ways to make the diff easier to read.

fix(cmd): only add options to relevant commands

---

src/dataFiles.ts

This prevents `cross-seed` from crashing in case something goes wrong.

fix(dataFiles): restart watcher on errors

---

src/action.ts

We only try to test linking with `ALL_EXTENSIONS` to avoid using OS files which will fail. Anything in `ALL_EXTENSIONS` should be fair to use. If none were found, the test for that path was skipped and no errors would occur.
Now we will create a file to test linking with if no existing ones are found. This will now throw an error if the user has a misconfigured empty drive.
The main reason for this is if the user has a drive with only games, we may not find a file to test with. But `getLinkDir` will fail when actually trying to link something unlike `testLinking`.

fix(linkDirs): fallback to temp file to test linking

---

src/action.ts
src/clients/Deluge.ts
src/clients/QBittorrent.ts
src/clients/RTorrent.ts
src/clients/TorrentClient.ts
src/clients/Transmission.ts

These very often have metadata changed but come out to the same size.

update(inject/resume): don't resume BD Disc

---

src/clients/QBittorrent.ts

`includeTrackers` is a new param added in qbit 5.1.0 that allows us to get the trackers for all torrents with the single `/torrents/info` endpoint. Previously, we would need to send an individual api request for each torrent, but wasn't a big deal since it only does that for first time users and the `cleanup` job.
`includeFiles` does not exist, but if it were to it would be handled the same.

ehancement(qbit): use includeTrackers includeFiles for info api

---

src/db.ts
src/torrent.ts

This adds a limit to the retries for snatches in the past day. Snatches will still be tried up to 5 times with a delay in between, but if all those fail, if this snatch fails again in the next day we won't retry. We will still always attempt it once.

enhancement(snatch): don't retry frequently failed recent snatches

---

src/inject.ts

Remove disc based content from recheck on reinjection.
Disc based content requires careful consideration and manual intervention, when the initial hash check fails to complete to 100%. autoresume is also disabled for disc based content for essentially the same reason.
Resuming failed hash check disc content will overwrite pieces in the existing torrent, and invalidate the existing torrent.
For this reason, recheck for disc based content on reinjection attempt, will never give a useful result, and will only ever increase drive wear and waste system resources.

enhancement(client/injection): prevent subsequent rechecks for disc images on reinjection attempts

---

src/action.ts
src/startup.ts
src/utils.ts

fix(startup): test permissions with temp file to support all filesystems

---

src/migrations/11-trackers.ts

The migration fails since it attempts to list files in TORRENT_CACHE_FOLDER before the folder has ever been created. This commit introduces a check to skip actions on files in that folder if it doesn't exist yet.
Fixes: #1052

fix(migrations): 11-trackers on new install
