- src/decide.js
Currently cross-seed will allow only identical files, down to the byte, but very often sites reupload the same torrents without nfo file, or without sample. My changes allow this, because these torrents still match the original. The change checks if every file of new torrent exists in the original torrent. I tested it with 200 entries, found few matches that cross-seed didn't catch before, zero false positives.
> Allow torrents with less files

- src/constants.js
- src/preFilter.js
Some shows may have over 100 episodes in a season, current implementation won't handle that. Also season regex won't catch situations like S01-10, it'll see only S01. For examples see:
https://regex101.com/r/HCc47S/2
https://regex101.com/r/hkMIfw/1
> Regex updates

- package-lock.json
- package.json
- src/decide.ts
This is the permanent fix for #46. It was fixed temporarily in https://github.com/mmgoodnow/cross-seed/commit/8385937bb39b57ed347f902037790b446a2be8d4 but that involved forking the parse-torrent package and referencing that fork in cross-seed's package.json. I was able to implement a custom solution using the original version of parse-torrent which is preferable because now I don't have to maintain the fork.
@Drazzlib08 I'm going to merge this in and cut a new release; please let me know if that bug comes back or if you see anything else that's funky.
> Write custom path checking using original parse-torrent library

- src/pipeline.ts
- src/server.ts
- src/torrent.ts
This pull request is related to the following Github issue: 
* #118
* None
* Merge code
> [FEATURE] - Allow daemon mode to search for torrents via hash

- src/cmd.ts
- src/startup.ts
- src/torrent.ts
- tsconfig.json
`trackers: []` in the fileConfig was casting out to string as `""` after a call to `.join("'")`, which is falsy. When I added notifications support I used the shared options function to make the test-notification command, but trackers are irrelevant, and I added what I thought was a nullish check to allow the user to silently pass no trackers but it was catching said falsy empty string. 
Solved by enabling optional chaining
> Fix bug when using an empty array to represent all trackers

- .idea/dictionaries/mmgoodnow.xml
- README.md
- package-lock.json
- package.json
- src/cmd.ts
- src/config.template.cjs
- src/config.template.docker.cjs
- src/configuration.ts
- src/constants.ts
- src/decide.ts
- src/jackett.ts
- src/logger.ts
- src/pipeline.ts
- src/runtimeConfig.ts
- src/startup.ts
- src/torznab.ts
- src/utils.ts
Closes #83 
Sort of unblocks #13
> Arbitrary Torznab support

- README.md
- src/cmd.ts
- src/config.template.cjs
- src/config.template.docker.cjs
- src/configuration.ts
- src/preFilter.ts
- src/runtimeConfig.ts
This PR changes to respecting the includeEpisodes flag even when searchAll is true.
I believe that this would be a useful change for two reasons
1. It exclusively adds functionality without removing it. It is still possible to regain the old functionality by using both searchAll and includeEpisodes. But there is a new option, searchAll without includeEpisodes, which was impossible before
2. Using searchAll without includeEpisodes is very useful. Including episodes takes far too long when you automate downloading new content, but without searchAll many legitimately cross-seedable torrents are skipped by the filter. For example, out of about 10,000 torrents searched, roughly on the order of 10% of them were not episodes but were filtered out when searchAll was false, even though matches …
> Respect includeEpisodes even when searchAll is true

- src/clients/QBittorrent.ts
- src/cmd.ts
- src/config.template.cjs
- src/config.template.docker.cjs
- src/configuration.ts
- src/runtimeConfig.ts
Closes #254
Behavior: 
- Sets up a category with the same savePath as the source torrent, but appends `.cross-seed` to the original category name.
- If the source torrent doesn't have a category, the injected torrent will also be uncategorized.
> Fix sonarr category issue

- src/server.ts
- website/docs/reference/api.md
Per discussion on Discord.
This changes the behavior for the `/announce` endpoint. 
Before: Send 200 OK on post with data if a match.
Now: Send 200 OK with data if match, and 204 No content if no match.
Why: to be able to easily use [autobrr](https://github.com/autobrr/autobrr) external filter to run cross-seed check early on.
> Send 204 if no match for announce POST

- src/clients/QBittorrent.ts
closes #249
before this PR, `Subfolder` torrents were injected as paused, rechecked, and resumed because of a bug in qBittorrent. As of https://github.com/qbittorrent/qBittorrent/pull/16825 (released as qBittorrent v4.4.3) that bug is fixed and we no longer need this workaround.
> Remove workaround for the qBittorrent Subfolder bug

- src/clients/QBittorrent.ts
Was causing .cross-seed to not get appended when duplicate categories was set to true.
> Fix category setup boolean

- src/config.template.cjs
- src/config.template.docker.cjs
Just small touches that I think can look better
> Chore: Improvement on config templates

- src/cmd.ts
- src/config.template.cjs
- src/config.template.docker.cjs
- src/configuration.ts
- src/runtimeConfig.ts
- src/torrent.ts
- src/torznab.ts
closes #386
This PR adds two options:
- `--search-timeout`/`searchTimeout`, in `vercel/ms` format.
- `--snatch-timeout`/`snatchTimeout`, in `vercel/ms` format.
These options govern the amount of time `cross-seed` waits for searches and snatches, respectively, before moving on. Both default to 30 seconds.
> Make timeouts configurable

- src/logger.ts
cleanse notifiarr url
current console output
`  notificationWebhookUrl: 'https://notifiarr.com/api/v1/notification/crossSeed/[REDACTED]-1234-568-9d05-1fghj1i678uik',`
this changes from /w to 0-9-a-zA-Z_- which covers `-` as well as `/w` 
also aligns regex with the torznab logic for consistency
> (fix) enhance logger cleansing of notification urls

- .github/workflows/ci.yml
Hi 👋🏼 
I don't see a reason to have the `version-` prefix on this tag but curious to know if there was a reason for it :)
This changes also makes it easier for automation tools like Renovate that expect semver to automatically sort and filter the tag correctly.
Thanks!
> chore: tag image with semver compliant container tag

- src/cmd.ts
- src/config.template.cjs
- src/config.template.docker.cjs
- src/configuration.ts
- src/pipeline.ts
- src/runtimeConfig.ts
The idea here is to limit the number of queries to be made between each running.
The current feature `excludeRecentSearch` can already filter off some results, so combined with a limit feature we can have more flexibility.
Example of my usage:
- My library has 440 items
- `excludeRecentSearch` set to `5 days`
- `searchLimit` set to `100`
- `searchCadence` set to `1 day`
Every day the search runs, it picks only the 100 that have not be done before
The user needs to pay attemption of their values or this can keep items out of the search, for example, if the `excludeRecentSearch` is too short for the limit, it will be start to pick items again...
fixes #432
> Feature: Search limit

- src/action.ts
If for any reason the `candidateParentDir` doesn't exist when doing a search match, ensure that it gets created on the fly.
This avoid issues where `candidateParentDir` isn't present during a match:
```
info: [torznab] Searching 12 indexers for Series.S01E03.2160p.WEB-DL.DDPA5.1.HDR.HEVC-NTb.mkv
error: ENOENT: no such file or directory, mkdir '/data/torrents/completed/others/Series.S01E03.2160p.WEB-DL.DDPA5.1.HDR.HEVC-NTb'
```
> Create the directory recursively when doing a path search

- src/pipeline.ts
Run the search on TorrentDir first as it will look for exact matches as a first order.
Currently cross-seed will process the dataDirs before considering a lookup of the torrentDir.
In practice, searches using the torrent dir allows to find exact matches to cross-seed. It requires fewer operations (no hardlinks) and uses the same category as the original torrent. It is overall "safer".
Because of this, it would be preferable to process the entire content of the torrentDir first, and only then do a more thorough lookup which may or may not get hits.
> Search torrentDir before dataDirs

- src/cmd.ts
Set a minimum cadence of once a day if excludeRecentSearch hasn't been set to avoid flooding requests
This limitation of 1 day is artificial to avoid spamming servers when doing lookups too frequently.
It is safe to assume that a  user that made use of the `excludeRecentSearch` option has put controls in place to avoid the said flooding, making that limitation unecessary.
Another option would be forcing the `excludeRecentSearch` to a day by default (it would have similar practical effects).
> Set a minimum cadence of once a day if excludeRecentSearch hasn't been set

- src/clients/QBittorrent.ts
Currently when doing a data based search, the injected content uses the default settings from qbittorrent when picking the content layout.
If the instance of qbittorrent uses `Subfolder` as the default content layout, cross-seed copies the content in the original layout and adds the torrent which can't be resumed as it expects the subfolder layout.
To counteract that, there are two options; copying the file in the right location (depending on the default layout set by qbittorrent); or forcing the layout to be `Original`.
This is the latter approach.
> Force the content layout when injecting file in qbittorrent

- .github/workflows/ci.yml
This skips all the steps involving pushing artifacts if running in a fork.
> Fix ci for forks

- src/preFilter.ts
The SQL query for the filterTimestamps function was malformed and would return the same (too high, low) timestamp every time, since it didn't filter for torrent name, and because max and min were reversed. It would never filter any torrent unless every single torrent had an extant entry in the db for every indexer.
Fixes cross-seed/cross-seed#453
> Fix search limit config item

- src/constants.ts
The following are changes made to improve matching for TV (season pack and episode) as well as movies.
* Replaced literal space (' ') in expressions with \s
* Changed <title> capture group to match lazily, reducing the total steps per match proportionally to the total string length after the second capture group.
* Added support for '_' in release name.
* Added support for '_' in release naming. (Does not use in season numbering range for multi-season packs)
* Capture multiple variations (including poorly named) of multiple season packs properly.
* Fixed matching incorrectly when season has more than one digit
* Added more variations on multi-episode capturing
If you run some test cases and find any outliers or mismatching, please comment and note what release naming you used to …
> fix(regex): movie and tv (pack and episode) regex

- src/torrent.ts
Self explanatory, was 0.25 before the rss prefiltering pr
> Revert treshold back to 0.25

- src/clients/QBittorrent.ts
href returns a trailing forward slash, which conflicts with using a static `/api/v2` cat'd for calling qbit.
> fix(qbitorrent): url-with-credentials compatibility fix

- src/clients/QBittorrent.ts
- src/utils.ts
added a `basePath` argument to `extractCredentialsFromURL` that should hopefully prevent us from making the same mistake I made again.
```js
> extractCredentialsFromUrl('http://admin:adminadmin@localhost:8080/qbit')
OkResult {
contents: {
username: 'admin',
password: 'adminadmin',
href: 'http://localhost:8080/qbit'
}
}
> extractCredentialsFromUrl('http://admin:adminadmin@localhost:8080')
OkResult {
contents: {
username: 'admin',
password: 'adminadmin',
href: 'http://localhost:8080'
}
}
> extractCredentialsFromUrl('http://admin:adminadmin@localhost:8080/qbit', '/api/v2')
OkResult {
contents: {
username: 'admin',
password: 'adminadmin',
href: 'http://localhost:8080/qbit/api/v2'
}
}
> extractCredentialsFromUrl('http://admin:adminadmin@localhost:8080', '/api/v2')
OkResult {
contents: { …
```
> Handle URL paths better

- src/clients/QBittorrent.ts
- src/constants.ts
- src/utils.ts
the regex previously captures separators trailing <title> capture group needlessly when separated with a space prior to SxxExx/Sxx (" - ") and will add the non-space separator to the search string. this usually applies when data searching an arr library/root folder.
this PR fixes this behavior and removes the separators after title from title's capture group.
(also removed unused variable from qbit injection function)
> fix(regex): title capturing trailing separator

- src/action.ts
- src/startup.ts
will not silently proceed to save if erroneous values are set for action in the config file.
- Fixes #478
> fix(logging/config): validates config file action methods

- src/clients/RTorrent.ts
Closes #502 .
Tested on:
1. Single-file unrenamed torrent
2. Multi-file unrenamed folder
3. Single-file renamed (without its name in path) torrent
4. Multi-file renamed (without its name in path) torrent
Also checks the data for torrent resume correctly.
> Fix rTorrent injection incorrect paths

- .gitignore
- .idea/codeStyles/Project.xml
- src/action.ts
I noticed a bug with symbolic links while I was testing #503—symlinks were being created pointing to relative paths from the POV of cross-seed's working directory. 
Some other changes with mkdir— `recursive: true` will silently succeed if the directory already exists, so we are able to skip some `existsSync` precondition checks and some `try/catch`es as well.
> resolve relative directories before creating symlinks to them

- package-lock.json
- package.json
- src/clients/Deluge.ts
- src/clients/TorrentClient.ts
- src/cmd.ts
- src/config.template.cjs
- src/config.template.docker.cjs
- src/configuration.ts
- src/logger.ts
- src/runtimeConfig.ts
- src/startup.ts
- src/utils.ts
- tsconfig.json
This PR adds support for injection to Deluge v2 torrent clients.
- Closes #58 
- requires RpcUrl uses extractCredential function
- uses JSON-RPC endpoint in deluge's webUI
- utilizes node-fetch library for sending calls
- bare function documentation
- logging and validation of config
- returns InjectionResults properly with appropriate handling
- - [x] conform to current label usage behavior
- - [x] get deluge's webUrl to be redacted in logging
- - [x] standardize logging messaging
- More.....
> feat(client/deluge): injection support for deluge torrent client

- src/auth.ts
- src/cmd.ts
- src/config.template.cjs
- src/config.template.docker.cjs
- src/configuration.ts
- src/migrations/04-auth.ts
- src/migrations/migrations.ts
- src/runtimeConfig.ts
- src/server.ts
Hey!
This is simple implementation of adding auth to the API endpoints.
The apiKey can be set as:
- query param `/api/webhook?apikey=my-secret-key`
- as a header `X-API-KEY`.
If the `apikey` is set in the config file and it does not match it responds with `401 Unauthorized`.
Could be improved with a micro framework like Express or Fastify or similar that implements middlewares, but this is simple enough for the current 2 endpoints of the project.
The global var `secretApiKey` in `server.ts` might not be the best solution, but it works and makes it available to the needed functions.
:white_check_mark: Tested and it works as intended
Fixes #306
> feat(daemon): add API auth

- src/server.ts
this corrects the URL parsing for the api endpoint switch
currently, if you pass a URL parameter (`?apikey=`) the switch triggers a 404
Closes #542
> fix(api-auth): improper endpoint parsing with url parameter

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/parseTorrent.ts
- src/torrent.ts
- src/utils.ts
This PR adds some string sanitization to both the injection and saving of torrents where the name is used. This applies to some trackers that don't use normal file/folder structure and naming for their .torrents and then causes cross-seed to ENOENT on injection or incorrectly save.
Also addresses injecting into Deluge when the source is a torrent already in a '.cross-seed' label, will now check for the '.cross-seed' tag and not duplicate it to '.cross-seed.cross-seed'
> add(sanitization/actions): deluge-labeling (injection) and torrent filename (injection/save)

- src/clients/Deluge.ts
This PR implements a try block to prevent stack tracing when deluge fails to respond during validateConfig - this is not caught currently.
```Error: Failed to connect to Deluge at http://192.168.1.14:8112/json
at Deluge.call (file:///usr/src/cross-seed/dist/clients/Deluge.js:75:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Deluge.authenticate (file:///usr/src/cross-seed/dist/clients/Deluge.js:36:30)
at async Deluge.validateConfig (file:///usr/src/cross-seed/dist/clients/Deluge.js:24:9)
at async Promise.all (index 2)
at async doStartupValidation (file:///usr/src/cross-seed/dist/startup.js:29:5)
at async Command.<anonymous> (file:///usr/src/cross-seed/dist/cmd.js:180:9)
at async Command.parseAsync …
```
> fix(deluge/authenticate): capture errors in authenticate with try block

- src/server.ts
I think would be cool to say who is doing the announce.
Currently we only log if the injection happens.
> feat(announce): add tracker to announce log

- src/decide.ts
- src/server.ts
addresses potential problems when size is not provided in announce, which in autobrr results in "0" being provided as a size.
result is an automatic size mismatch, when it could/should otherwise be discarded as erroneous
> fix(announce/size): ignores erroneous size being used ("0")

- src/migrations/02-timestamps.ts
How to reproduce: on a clear environment run `cross-seed api-key`
```
migration file "02-timestamps" failed
migration failed with error: Cannot destructure property 'torznab' of 'getRuntimeConfig(...)' as it is undefined.
file:///usr/local/lib/node_modules/cross-seed/dist/migrations/02-timestamps.js:10
const { torznab } = getRuntimeConfig();
^
TypeError: Cannot destructure property 'torznab' of 'getRuntimeConfig(...)' as it is undefined.
at backfill (file:///usr/local/lib/node_modules/cross-seed/dist/migrations/02-timestamps.js:10:13)
at Object.up (file:///usr/local/lib/node_modules/cross-seed/dist/migrations/02-timestamps.js:42:11)
at async Migrator._runBatch (/usr/local/lib/node_modules/cross-seed/node_modules/knex/lib/migrations/migrate/Migrator.js:381:19)
```
The commands `api-key` …
> fix(migrations): set config initial value

- src/torrent.ts
previously we were explicitly _not_ following redirects so that we could intercept redirects to magnet links, but that was a workaround because the errors thrown by redirecting to magnet links were uncatchable. Since we've switched to fetch, that's no longer a problem and we can now catch the errors caused by redirecting to magnet links, and let fetch follow the redirects otherwise. 
#549
> follow 3xx redirects on snatch

- .eslintrc.json
- package-lock.json
- package.json
- src/clients/Deluge.ts
- src/clients/RTorrent.ts
- src/clients/Transmission.ts
- src/configuration.ts
- src/decide.ts
- src/jobs.ts
- src/migrations/02-timestamps.ts
- src/parseTorrent.ts
- src/pipeline.ts
- src/preFilter.ts
- src/pushNotifier.ts
- src/runtimeConfig.ts
- src/searchee.ts
- src/server.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
- tsconfig.json
This PR updates our TypeScript configuration to allow ES2022 features, and turns on `strictNullChecks`. 
A few of our existing patterns don't really play nice with `strictNullChecks` and I used the non-null assertion operator `!` pretty liberally to fix the issues. 
The optional property `metafile` is implicitly tied to `decision` having a value of `MATCH` or `MATCH_SIZE_ONLY`. We should make this explicit at some point by making it a union type.
```ts
export interface ResultAssessment {
decision: Decision;
metafile?: Metafile;
}
```
This has the same problem. The optional property `infoHash` is implicitly tied to `path` not existing. We could make this explicit at some point, though we also might want to support both existing. 
```ts
export interface Searchee {
infoHash?: string; // if …
```
> Update Typescript config

- src/constants.ts
- src/decide.ts
adds to decide.ts the condition that release groups match before snatching the torrent for comparison
- risky matchMode will not require both groups to be present to snatch
- safe matchMode will require both groups match
- groups are case-insensitive
> feat(decide): release group match prior to snatch

- src/decide.ts
a few trackers truncate release names after certain lengths, leaving the possibility (although needs to be the right length) for groups to be truncated and partial groupnames returned from Torznab.
While the truncation will not always be mid-groupname - this will provide a marginal amount of matches that otherwise would not be snatched.
Potentially could use a "blacklist" for producing no-match when group name evaluates to something like "-DL" or something, to catch WEB-DL when truncated prior to the group name start, however this is a bit iffy too.
> update(group-matching): use startswith for group matching

- Dockerfile
- src/cmd.ts
After node v20.6 we can use native env files. https://nodejs.org/en/blog/release/v20.6.0
- The `.env` file needs to exists in the current dir: 
- in case of docker is already the /config
- if installed with npm or anything, the current dir (`pwd`) is considered (it can be changed on many way, eg systemd uses `WorkingDirectory`)
- if theres no `.env` file, no error or warning, no side-effect
And just use `process.env` as normal
> adds support to .env file using native feature

- Dockerfile
- package-lock.json
- package.json
- The better-sqlite3 v9 have improvements regarding the node-gyp and build issus that we had
- see changelog after v9 https://github.com/WiseLibs/better-sqlite3/releases
- Regenerate the package-lock for node@20 and npm@10 to improve the peer dependencies as well
> Regenerate package-lock and bump better-sqlite3

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/configSchema.ts
- src/configuration.ts
- src/decide.ts
- src/runtimeConfig.ts
completes tracker subdir in linkdir for torrent linking to #563 
-  - [ ] check autotmm implications
- - [x] transmission
- - [x] rtorrent
- - [x] deluge
- - [x] qbittorrent
- more soon
> feat(linking): support linking for torrent-backed searchees

- src/decide.ts
when rejecting a release in decide.ts - if the rejection is due to file size distinguish between this and general file-tree mismatch
> update(decide/logging): distinguish size over filetree mismatch when rejecting

- src/constants.ts
- src/decide.ts
fixes a failure to match on both missing groups when matchmode is safe
addresses huno's renaming scheme and matches properly with other trackers
> update(group-match): fixes matching conditions in safemode and tracker compatibility

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/constants.ts
- src/pushNotifier.ts
Moving the tag and category to `constants.ts`
This would make it easy to patch and also reduce magic const.
There is also one fix on `cmd.ts`, it was breaking on me due missing array errors, so I just made an safe type there.
> chore: move category and tag to constants

- src/cmd.ts
- src/configuration.ts
If a user's config file has invalid syntax, cross-seed throws the raw `SyntaxError` from node trying to `require` the file. This PR adds some error handling to catch-and-rethrow a friendlier, more actionable error message than what the SyntaxError showed.
> feat(config/logging): error messaging on invalid syntax in config file

- src/torznab.ts
If an indexer failed with a non-429, it may be due to a configuration issue. This is frustrating for new users because they are working on getting their configuration correct and then if something breaks, they have to wait 10 minutes until they can continue.
This PR clears out any saved UNKNOWN_ERRORs on startup, allowing users to freely tinker with their configurations.
> Reset cached indexer failures on startup

- src/config.template.cjs
- src/config.template.docker.cjs
Minor edit to the config to make it clear that previously failed searches will not be excluded, and hence that the usage of excludeRecentSearch can also be used to search for previously failed searched.
> add(config/excludeRecentSearch): disclaimer about failed searches

- src/config.template.cjs
Extend comment lengths to ~same length as a torznab entry from Jackett. Seems to also be the same comment length as other areas already in the config.
Minimizes line breaks.
Other minor adjustments.
> update(configs): Consistent comment lengths (80 character), minor adjustments

- src/clients/Deluge.ts
this PR adds a 10 second timeout for all Deluge calls, and also moves error handling for labeling from a global `catch` in `inject` into the `setLabel` method.
> fix(client/deluge): defend against deluge timeouts

- Dockerfile
- src/cmd.ts
Small change here, tzdata lets users set TZ env with their timezone and [catatonic](https://github.com/openSUSE/catatonit) is a tiny init manager which won't cause problems.
> ci(docker): add catatonit and tzdata to image

- Dockerfile
Goes back to previous behavior
> fix: remove CMD from `Dockerfile`

- src/configSchema.ts
- src/jobs.ts
- src/torznab.ts
I use autobrr to send announcements to cross-seed and do not need any indexers defined in the config as I don't use the search functionality. It would be nice if this warned the user instead of throwing an error.
> feat(daemon/announce): daemon functionality without torznab defined

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
closes #602 
initially had a misunderstanding of the issue...going over some of the older addressable issues I now understand what was said
this addresses #602 by ignoring `dataCategory` when assessing whether to `duplicateCategories` or not
the assumption is, `dataCategory` will never interfere with an import category for an "arr"
> update(duplicateCategories): ignores appending cross-seed to dataCategory

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/constants.ts
- src/decide.ts
- src/pipeline.ts
Replacement for #614 as the previous base branch was deleted and it can no longer be updated. Apologies for the complications.
Implements #610 and all changes in comments and review of previous PR. Also ensuring torrents are added in paused state if skipRecheck is false for partial matching and reporting FILE_TREE_MISMATCH there are duplicate sizes without a name match.
> feat(decide/match): partial file tree match mode

- src/action.ts
- src/constants.ts
- src/pipeline.ts
- src/searchee.ts
- src/torznab.ts
- src/utils.ts
Implements: #631
To summarize, this feature has zero effect on anything non-anime and correctly parses the vast majority.
---
Did a lot of digging into anime and the best way to match correctly. My goal for this PR is to do it right from the start, it should not be possible to make a meaningfully better regex for anime. I avoided covering edge cases but there is like 5 common formats used and more information to track like [tags] and altTitle, so the regex ended up being long anyways.
I got ~35,000 unique titles from nyaa dating back to 2019 in both English and non-English translated anime. Ran these data progressively through the regex in order (ep, season, movie, anime) noting any improvements that can be made to the existing regex. Each time I would remove what matched to simulate what …
> feat(regex): Improving anime matching

- src/decide.ts
- src/indexers.ts
- src/preFilter.ts
- src/utils.ts
closes #578 
this adds verbose logging for the local size and candidate cross-seed size and release group mismatches appended to the `[decide]` line as well as the matching string for blockList when a release is blocked
formatting appended to reason: `(<local> -> <candidate>)`
ex: `2024-04-18 02:34:54 verbose: [decide] Show.S01.1080p.BluRay.x264-GRP- no match for tracker torrent  Show.S01.1080p.BluRay.Remux.DTS-HD.MA5.1.H.264-GRP - its size does not match - (42.6GB -> 103.8GB)`
> feat(logging): mismatch decisions note searchee-candidate differences

- src/clients/QBittorrent.ts
This was called from a feature I'm testing
`2024-04-19 22:01:29 error: TypeError: e.includes is not a function`
This was caused when getting the downloadDir for all searchees without a .path.
It successfully finds the info hash in client via `isInfoHashInClient` but fails when getting torrentInfo from `getTorrentConfiguration`. The root cause seems to be the /torrents/info from getTorrentConfiguration sometimes failing:
`error: TypeError: fetch failed
at node:internal/deps/undici/undici:12618:11
at async QBittorrent.request (file:///usr/src/cross-seed/dist/clients/QBittorrent.js:47:26)
at async QBittorrent.getTorrentConfiguration (file:///usr/src/cross-seed/dist/clients/QBittorrent.js:122:30)
at async QBittorrent.getDownloadDir (file:///usr/src/cross-seed/dist/clients/QBittorrent.js:105:23 …
> fix(client/qbittorrent): missing message property in error.includes

- src/action.ts
- src/arr.ts
- src/indexers.ts
- src/migrations/05-caps.ts
- src/migrations/migrations.ts
- src/torznab.ts
- src/utils.ts
filters out indexers per search who dont have the media type being searched for, the result ends up requiring dual messaging for timestamp and category filtering. I'm not sure if this matters, i just merged the message.
currently based off id-search branch, so targeting that for now.
> feat(torznab/indexer): filter out indexers without mediatype category

- src/clients/QBittorrent.ts
The problem stems from the fact that we are using infoHash in searchee. If the torrent in qbit is using infoHashv2, then it won't return any results.
Calling `isInfoHashInClient` was redundant as it was handled in `getTorrentConfiguration`. This reduces the api calls to qbit and handles the case of missing infoHash.
> fix(client/qbittorrent): unhandled branch causing undefined property access

- src/cmd.ts
this clears all values in the indexer table relevant to enabling the indexer.
i don't think we should advertise this command in docs, but i think it would benefit support when a user doesn't have to clear their entire db to get around a rate limiting from torznab that would otherwise last 24hours but was really only necessary to back-off for an hour.
has happened enough times that i wish it was available for support.
> feat(clear-indexer): adds cli argument for clearing indexer stats

- src/constants.ts
- src/searchee.ts
- src/torznab.ts
- src/utils.ts
Since we are restricting searches based on category, we might as well add these in to further limit. Not official support for searching (not even sure if we can make improvements).
I put music and audiobooks into audio since they have the exact same extensions. I also preferred audio over book so if a release contains a book and audio book, it gets marked as audio.
I also put comic/manga with books. As there is some overlap in .pdf but mainly just to reduce clutter.
getTag now just takes a searchee rather than isVideo as the extension checking is done for all media. Should we put getTag in searchee.js? Only uses are with searchees and causes imports to utils.js.
> feat(torznab/indexer): filter out indexers without audio and book category

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/runtimeConfig.ts
This PR renames the `dataCategory` option to `linkingCategory`, renames the `legacyLinking` option to `flatLinking`, and updates a couple surrounding things (changing the default value of linkingCategory to `cross-seed-link` instead of `cross-seed-data` and some small copy updates.
> Rename flatLinking and linkingCategory options

- src/clients/Deluge.ts
since every id is independent to a connection, using random will create the potential for a bad seed to produce duplicates.
starting at 0, we will now increment through the id last used.
this change was due to new information i was previously unaware of (independent per connection) given to me by a developer on the team
> fix(client/deluge): incremental id with json-rpc requests

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/labeler.yml
- .github/workflows/labeler.yml
sets up templates for issues with a bunch of requirements, acknowledgements, and questions.
configured a label workflow to automatically assign triage to all PR's based on modified files, as well as relevant labels for files modified.
once someone manually checks the triage'd PRs, removing the triage will signify that it has been labeled by a human
> feat(git-workflow): add templates and labeling for PRs

- src/clients/QBittorrent.ts
`isSubfolderContentLayout()` was basically always returning false. Updated the check and is correct from my testing. Also simplified `getDownloadDir()` as it was making unnecessary calls and checks.
> bug(client/qbit): Check for subfolder when linking and properly set category

- src/torznab.ts
- src/utils.ts
Requires movies to pass the regex and contain a video file. This prevents audio and books with years in the title from matching. Episodes and seasons do not need the check.
shouldSearchIndexer also updated to search if MediaType is other rather than not. The checked categories are enough of a restriction on useless searches and so we should assume an edge case in this scenario.
Also now checks for extension on file names rather than searchee name.
> enhancement(utils/arr): refactor getTag() and formatTitleForSearching() around MediaTypes

- src/constants.ts
- src/decide.ts
if the release group does a repack or propers, this release is certainly not the same as the previous and not cross-seedable.
this filters (last in the chain of filtering) whether the searchee and candidate are of the same "type" - repack and proper as well as repack# are supported.
considered adding internal, but not all trackers tag internals as such and could result in false-negatives
risky/partial will still operate on the basis of if there is a proper or repack in the name it returns true regardless of if they match to work with their aggregating of REPACK and PROPER into a PROPER.
if searchee matches arr's naming then it will act based on risky/partial being set.
> feat(decide): adds subsequent releases by same group filtering

- src/action.ts
- src/clients/QBittorrent.ts
Did some digging into how subfolder layout is handled. It should be completely fixed now. Problem was if a torrent with a single file that naturally had a folder, it would get the incorrect path.
Also getting torrent info in a way that doesn't rely on infohash versions.
Potentially fixed bug with rechecking searchee instead of newTorrent in deluge.
> bug(clients/qbit): Properly handle subfolder layout

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
This updates the linking for MATCH and MATCH_FILES_ONLY to support the new sourceRoot which handles subfolder layout. This was done in the style of MATCH_PARTIAL.
Also updated the timeout before rechecking to 1s in qbit and deluge.
> bug(action/linking): Linking dest files properly

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/constants.ts
- src/decide.ts
- src/utils.ts
> migration(v6/qbit): refactor and migrate to v6 category and tagging

- src/configSchema.ts
- src/startup.ts
had inverted logic of `path === '.'` instead of `!==`
inverted the logic to allow for `.` as a path.
> fix(zod/checkvalidpath): move path formatting logic after fs validation fails

- src/pipeline.ts
in the case of windows users using a drive letter only for their paths (`X:\\`) then mkdir will fail for operation not permitted, as you cannot create a drive letter.
this will check if the path exists before creation, if so it wont attempt to create it preventing a stack from being thrown.
```node:fs:1373
const result = binding.mkdir(
^
Error: EPERM: operation not permitted, mkdir 'Z:\'
at Object.mkdirSync (node:fs:1373:26)
at main (file:///C:/Users/Audio.Main/AppData/Roaming/npm/node_modules/cross-seed/dist/pipeline.js:183:8)
at async Command.<anonymous> (file:///C:/Users/Audio.Main/AppData/Roaming/npm/node_modules/cross-seed/dist/cmd.js:235:9)
at async Command.parseAsync (C:\Users\Audio.Main\AppData\Roaming\npm\node_modules\cross-seed\node_modules\commander\lib\command.js:923:5)
at …
```
> fix(pipeline): check existence of path before creation

- src/clients/Deluge.ts
refactors deluge to use the Result class rather than simply throw'ing
also fixes errors deluge would throw when trying to set labels that were not present. deluge would throw RPC error's, and we would base adding off that. now we get the current labels and decide whether to add or only set the label.
added jsdocs for kicks.
> refactor(client/deluge): switch to using Result class for calls

- src/action.ts
- src/searchee.ts
1. When linking MATCH, check if searchee.files.length = 1 instead of newMeta.files.length = 1 as newMeta can contain less files than searchee even for a perfect match.
2. Check if sourceRoot isFile() with fuzzyLinkOneFile() as searchee.path could be a directory but only contains a single file (usually not searched due to de-duplication preferring torrents).
3. Updated searchee creation from path to ignore searchees with no files (empty folders).
> bug(action/link): fix incorrect link paths when linking single file

- src/constants.ts
The movie `A.Whisker.Away.2020.1080p.BluRay.Opus5.1.H.265-LYS1TH3A.mkv` was matched as an episode due to the `Opus5.1` where `s5` was season and `1` was episode.
This matched due to the support for `SXX - E?YY` anime format. But it turns out that `.` is never used instead of `-` or `_` here so it can safely be removed.
Also found `Haunted.Mansion.2023.1080P.Bluray.TrueHD.Atmos7.1.Hybrid.DoVi.HEVC.X265-FZHD` where `Atmos7.1` has the same issue.
> fix(regex): movie matched as episode

- src/clients/QBittorrent.ts
- src/config.template.cjs
This prevents hardlinks from breaking when a torrent is moved from/to the `save_path` after rechecking a match partial and completing the torrent. Only matters if the user's `downloadPath` is on a different drive. Tested and working in qBittorrent. Need to address for other clients as well.
> fix(clients): set download path when adding torrent

- src/action.ts
- src/arr.ts
- src/torznab.ts
addresses a typo in the relevantId function as well as additional logging surrounding mediatype and linking failures
> fix(arr/id): address typo and additional logging details

- src/Result.ts
- src/action.ts
- src/arr.ts
- src/clients/Deluge.ts
- src/clients/RTorrent.ts
- src/clients/Transmission.ts
- src/decide.ts
- src/pipeline.ts
- src/torrent.ts
The current Result type is okay, but it doesn't actually leverage Typescript's ability to catch bugs at build time. This PR does a few things:
- Result is now a **union type** of `OkResult | ErrResult`
- `unwrapOrThrow(err?: Error)` has been separated into two methods:
- `unwrap()` this method ONLY exists on OkResult. In order to call it, you need to use `isOk` or `isErr` to do type narrowing so that TypeScript knows the method exists. 
- `unwrapOrThrow(err: Error)` This is a convenience method to throw an error if the result is an ErrResult. It is like the old version of `unwrapOrThrow`, except the argument is now required. This exists on BOTH OkResult and ErrResult. 
- I migrated all calls to `unwrapOrThrow()` with no arguments to use `unwrap()`, and kept calls of `unwrapOrThrow(new …
> Refactor Result type

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/constants.ts
- src/decide.ts
- src/pipeline.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
This mainly is to support multi-file risky based matching moving the 100% MATCH_PARTIAL matches to MATCH_SIZE_ONLY. I refactored decide.js to the state it will be downstream.
1st commit:
1. The priority of decisions 
2. Reporting more granular decisions
3. Caching all snatched .torrent files and saving infoHash with decision if present (might as well start doing this now for `cache-search-queries`). We can optionally cleanup based on modified time since it is updated each time it's used.
4. Better error message for decisions and snatch.
2nd commit:
1. Support multi-file risky based matches
> enhancement(decide/match): support multi-file risky based matching

- src/cmd.ts
- src/configSchema.ts
- src/constants.ts
when using a value over max signed int cross-seed will default back to 1s, producing searching behavior that essentially hammers your indexers rather than producing any semblance of a longer timeout
closes #704
> fix(search/delay): value over max signed int produces default to 1s

- src/clients/Transmission.ts
corrects the throw resulting from a non-json response being a `SyntaxError` rather than `TypeError` which results in logging incomplete errors
closes #702
> fix(client/tm): transmission logging for non-json response

- src/constants.ts
- src/decide.ts
fixes incorrect matching in cases of, for example,"Repack" being used in releases when "REPACK" is the original in either candidate or searches
splits the arrtype and proper/repack into two regex
closes #700 
- remove reliance on checking for file extensions in group regex to determine group - used stripextension prior to applying regex instead
- separate proper from arr format and case-insensitive formatting, adds a condition that candidates be a repack/proper when searches is identified as a repack/proper when its possible the searchee is from an arr library
- fix periods not being accounted for in group regex when present in group name
- https://regex101.com/r/FqOjtj/6 (group regex with test cases)
> bug(decide): fix incorrect matching due to case and punctuation

- package-lock.json
- package.json
- src/action.ts
- src/constants.ts
- src/decide.ts
- src/logger.ts
- src/pipeline.ts
- src/torznab.ts
- src/utils.ts
Logging improvements that were made across branches. Also added a new dependency strip-ansi from the same maintainers as chalk. This removes the ansi codes that clutters up the logs but keeps them in console. Also redacting more sensitive information.
> update(logging): Strip ansi from logs and general logging improvements

- src/logger.ts
This mirrors the configuration I added as an override to the `Console` transport. I must have just forgotten to add it to the default formatter
> fix(logging/stack): add stacktraces to log files

- src/logger.ts
apiKey from config is logged in plaintext in the configdump.
this PR removes any apiKey value from being logged.
```js
apiKey: [REDACTED],
```
> fix(logging/config): redact apiKey from logging in configdump

- src/decide.ts
- src/torznab.ts
- src/utils.ts
[From discord](https://discord.com/channels/880949701845872672/1249298183452885046/12492981834528850460)
`Name: Love Island S11E06 Unseen Bits `**1080i**` HDTV DD2.0 H.264-DARKFLiX`
`File: Love.Island.S11E06.Unseen.Bits.`**1080p**`.HDTV.H264-DARKFLiX.mkv`
`verbose: [decide] Love.Island.S11E06.Unseen.Bits.1080p.HDTV.H264-DARKFLiX - no match for BeyondHD torrent Love Island S11E06 Unseen Bits 1080i HDTV DD2.0 H.264-DARKFLiX - its resolution does not match: 1080p -> 1080i`
The video is actually 1080i but the scene release was named 1080p, and only BHD decided to be diligent and correctly call it 1080i in the release name, while keeping the file.
> enhancement(decide/res): ignore resolution type

- src/indexers.ts
- src/jobs.ts
- src/torznab.ts
1. `getEnabledIndexers()` no longer returns indexers with null caps. Which is possible if an indexer was down every time `cross-seed` was restarted since migrating to v6.
2. Caps are refreshed before `search` and `webhook`, not just on startup. This prevents the change above from being a silent failure if users don't restart `cross-seed` for a long time. Also benefits in the normal case as indexer caps will always be in sync without needing a restart.
> bug(indexers): skip indexers with null caps and refresh with indexer job

- src/action.ts
- src/arr.ts
- src/torrent.ts
The unlink logic was pulled from the `inject-saved-torrents` branch so it has been used for a while without issues. I've expanded it to cover the bug here [from discord](https://discord.com/channels/880949701845872672/1228878509414420594/1250084947985694721). Torrents with the same hash from different trackers would still be linked with `flatLinking: false`.
I also starting saving torrents when source is incomplete, which is for the inject feature but we can start doing this now.
> enhancement(action/unlink): unlink failed injections and save incomplete torrents

- src/constants.ts
scene groups are almost exclusively lowercase when implemented, so this strictly checks that the characters matching in the 0-5 occurrences are all lowercase or numeric in value
- https://regex101.com/r/QvFUyF/4
> fix(regex/scene): require scene group in prefix be lowercase

- src/cmd.ts
fixes cli not accepting multiple arguments for `--block-list`
> fix(cli/blocklist): allow multiple arguments for cli usage

- src/arr.ts
Sonarr recently added TMDB support for which some ids are 0. It may be temporary but we should cover it regardless.
> fix(arr/ids): consider ids of 0 invalid

- src/arr.ts
- src/torznab.ts
adds support for tvmaze in id searching and caps
does not need a migration since the caps are stored in json/string in the database
implementation is the same as previous ids
> update(id-search): support tvmaze id lookup

- src/constants.ts
- src/preFilter.ts
Single episode torrents with extra files would fail the single file check. It only uses the `EP_REGEX` to perform this test.
~The new multi episode test covers the cases that sonarr allows for renaming.
https://regex101.com/r/OEZqQx/2~
> fix(prefilter): remove single file constraint for isSingleEpisode check

- src/constants.ts
This just prevents 19XX|20XX from being episode numbers. Which if course prevents actual episodes of that number from matching, but that only happens in case of anime absolute formatting. And very few anime are that high. While it's much more common for the episode number to match a year in two scenarios:
1. `EXX 2024`
2. SXX `2024`
https://regex101.com/r/i0igR5/6
This was not changed for the anime regex since it already parses years.
> fix(regex/ep): years cannot be episode num

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
This updated check is only necessary for the `inject-saved-torrents` feature. Due to how it's handling injection, it was possible to unlink files that it just tried to link which defeats one of it's features.
This current change more explicitly defines when we would want to unlink in case of `ALREADY_EXISTS`. Only the changes in action.ts, specifically `rmSync` and the check added before unlinking are new. The updated `getDownloadDir` function was pulled from the `ensemble-matching` branch which just allows getting the savePath for incomplete torrents.
> fix(action/unlink): use stricter test for unlinking if injection already exists

- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/constants.ts
- src/dataFiles.ts
- src/pipeline.ts
- src/preFilter.ts
- src/pushNotifier.ts
- src/runtimeConfig.ts
- src/searchee.ts
- src/utils.ts
when a path is sent via webhook or search command and matches what was previously IGNORED_FOLDERS (SONARR_SUBFOLDERS_REGEX now) regex, we will parse the path for the parent folder (series) and the dirname (season) to cart the searches. this will allow risky/partial matching to parse the path and conduct meaningful searches for sonarr libraries
- this allows for sonarr libraries with season folders to be parsed and effectively searched with valid queries, as well as enabling season packs sourced from usenet to be searched upon completion with an import script where otherwise "Season 01" would be ignored entirely or searched erroneously as "Season 01" yielding non-matching results in 99% of cases.
- also enables includeEpisodes to effectively filter out against season folders in sonarr …
> feat(search/sonarr): add path parsing and support for sonarr season folders

- package-lock.json
- package.json
- src/arr.ts
- src/constants.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
This replaces the Fuse method of reverse lookup to leveraging the existing regex. Only the title, season, episode is used. All other parts should be handled in the decide stage. The title is cleansed as much as possible then converted to lowercase and with symbols and spaces removed. This is already much better than the Fuse, but we then add a fuzzy using the levenshtein distance. The max distance is `Math.floor(cleanTitle.length / 4)` so short titles needs to be exact and longer titles get more leeway. I haven't come across a situation where we need this fuzzy, but I'm sure they exist.
This method vastly outperforms Fuse in all aspects.
1. It's much faster. It's always ~50ms to get all matching items from the database for me. Where Fuse took 150ms if nothing was found up to multiple …
> enhancement(reverselookup): using regex to parse rss/announce names instead of Fuse

- src/config.template.cjs
- src/pipeline.ts
- src/preFilter.ts
- src/torznab.ts
`cross-seed search` will now never perform duplicate queries. After searchee creation, the torznab search is calculated for each and those with the same are grouped back to back. When searching, the `IndexerCandidates` from the last search is cached and if it applies to the current search will be used (the map will ALWAYS have a size of 1, indexers not searched by previous are searched and added to cache). This allows duplicate queries to only hit each indexer once (per `cross-seed search`) and to be assessed near each other. This is mainly useful if you have multiple variations of a torrent like: different groups, resolution, source, etc which are not duplicates but will have duplicate queries. From my testing, my queries were cut in half.
These grouped searchees are ordered by most …
> feat(search/cache): use cache to remove duplicate queries

- src/torznab.ts
this PR addresses media types we do not natively support, but should prevent from making absurd or erroneous queries that may result in excessive and inaccurate results - potentially overwhelming cross-seed during matching and creating a bottleneck.
logs from the reporting user showed their query for a music album resulted in nearly 50k results, and while this is absurd is mainly due to the query strings we send and a lack of truncation on the tracker (which is dumb too lol)
to address this, I've done the following
* clense the seperators (ONLY) for unsupported mediatypes, since parsing anything out is going to be mostly irrelevant for this.
> fix(torznab/search): better queries strings for unsupported media

- src/arr.ts
- src/pipeline.ts
- src/torznab.ts
No issues have been found, but we should do this just to be safe. Since there could be differences between raw searches and id searches, we should verify both.
Also now using a custom type instead of map which fits better its purpose.
> fix(search/cache): verify ids before using cached search

- src/decide.ts
- src/pipeline.ts
Some trackers frequently announce before it's possible to snatch. Now if a snatch fails from rss/announce, we wait 30s before resnatching. The added delay is not a concern as 99.9% rss/announce won't pass the reverse lookup and even fewer will attempt snatching.
This is done instead of returning a 202 for announce so a snatch can only happen twice rather than users current retry attempts.
> enhancement(decide/snatch): retry rss/announce snatch after delay

- src/pipeline.ts
- src/preFilter.ts
- src/pushNotifier.ts
Previously would not search if a path based criteria for webhook was supplied and it was in a season folder. Will no longer check if season pack episodes from webhook searches.
Also using metafile.name for notifications since searchee.name can be artificial.
> fix(preFilter): search season pack episode from webhook if includeSingleEpisodes

- src/arr.ts
- src/clients/QBittorrent.ts
- src/logger.ts
- src/torznab.ts
- src/utils.ts
This aims to prevent searching for media that can't exist on the indexer for unknown media types as well.
* If the searchee contains a video, always search unknown media type
* Otherwise only search if the indexer has additional categories (ones not explicitly recognized by cross-seed)
Also now matching `MediaType: MOVIE` for .rar releases. Before it was just a logging thing and maybe some uncessary api calls to sonarr. But is now necessary with this new behavior.
> enhancement(search): search unknown MediaType only if supported by indexer categories

- src/cmd.ts
- src/constants.ts
- src/decide.ts
- src/migrations/06-uniqueDecisions.ts
- src/migrations/migrations.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/torznab.ts
- src/utils.ts
Updated how decision cache is handled so that users will never need delete the database or `cross-seed clear-cache` for v6 and beyond. For most decisions, it will reassess as the cache could get invalidated in many ways by config changes or future updates. To better assist this, caching has been updated to take advantage of the `inject-saved-torrents` feature of matching without snatching if the torrent exists in `torrent_cache`. In addition, all .torrent files that are snatched, not just successful matches, will now be saved in `torrent_cache`. Cache .torrent files are retrieved by the candidate guid only, so similar searchees don't need to resnatch. The priority of decisions has also changed to better handle fast paths when cached. With these changes, torrents are only ever snatched …
> feat(decide/cache): retry cached decisions

- src/cmd.ts
- src/configSchema.ts
for many users, overriding the exclude time-based variables via cli has been valuable for searching, with zod this is not possible due to requiring ms formatting.
this PR allows the `--no` prefix to be used in commander (cli) for the cli parameters
`--no-exclude-older`
`--no-exclude-recent-search`
> update(schema/cli): allow override with --no of config for exclude options

- src/preFilter.ts
this PR adds the ability for data-based searches to match the directory a file resides in
this is particularly useful for "Extras", "Trailers" and "Featurette" folders often associated with media servers such as plex, JF, and emby.
this also allows for blocking of entire directories in data based searches rather than requiring each individual file be added to the blocklist
> enhancement(blocklist): matches directory name of files for data-based searches

- src/arr.ts
- src/cmd.ts
- src/constants.ts
- src/decide.ts
- src/diff.ts
- src/parseTorrent.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
Fixes:
1. `SEASON_REGEX` no longer matches episodes
2. `SEASON_REGEX` matches titles that end with the season
Now parsing `Season XX` or `SXX` titles from torrent based searchees as well. This required keeping track of the parsed title in the new `title` field. `title` is equal to `name` in all other scenarios.
The two places where `name` is now being used is for linking and client logging. Those require the original name. Otherwise `title` is better for searching, logging, and `searchee.name` in database (different shows won't collide).
As a bonus I added this for the anime releases that are just the show name. So if the torrent title is `Show` and it has a single episode, we will use the episode name as `Show SXXEYY`.
> enhancement(searchee): parse 'Season XX' or 'SXX' torrent titles

- src/configSchema.ts
- src/decide.ts
- src/preFilter.ts
due to the inability to configure specific exclusions from RSS and autobrr's ability to exclude things from announce in filters, it seems prudent to remove the exclusion of RSS when set to false and only have announce be exempt.
for users wishing to exclude single episodes from their announce, [this is configurable from autobrr](https://autobrr.com/filters/examples#only-season-packs) and is not reliant on this setting in cross-seed to accomplish the same goal.
this allows for announce to be used to cross-seed single episodes, when searching for single episodes is not desired the option can still be set to false to relieve stress on API calls to indexers during searches.
> revert(includeSingleEpisode): remove exemption behavior with rss when false

- src/clients/Deluge.ts
- src/searchee.ts
- src/server.ts
- src/torznab.ts
there is no timeout set on fetchCaps - which depending on the number of indexers can delay config validation for what seems like indefinitely to a user with prowlarr/jackett not responding. this introduces a 10s timeout on cap fetching, which should be almost instant minus latency between cross-seed and prowlarr/jackett, as the indexer is not queried for this.
also added some sanity checking on webhook parameters, checks for correct length of infohash and the validity of a path on the fs before proceeding
> update(logging/checks): adds timeout on cap fetching and validates webhook params

- src/searchee.ts
- src/utils.ts
Will also now return the original name if a better couldn't be found if it's no `Season X`. These searches can still have value.
> fix(searchee): correctly parse date episodes and skip parsing non-video

- src/decide.ts
Lots of users were confused by the original message, this should make it unambiguous as to why it was rejected.
> logging(decide): clarify logging around size mismatch

- src/utils.ts
when certain release names, usually non-standard or unsupported media, end with a hyphen this can be appended to the search string erroneously. 
I've done the same for the beginning of the query as well for completeness.
example: `Gav Thorpe - Catechism Of Hate - [epub]`
[epub] is excluded in `cleanseSeparators` and thus a trailing - is appended to the string due to hyphens not being cleansed at all.
resulting query: `t=search&q=Gav+Thorpe+-+Catechism+Of+Hate+-`
this PR checks for preceding and trailing hyphens and removes them
> fix(search): remove erroneous hyphens in torznab queries

- src/arr.ts
- src/constants.ts
- src/searchee.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
This is often gets removed causing issues with non id search. Movies should keep it however since it's consistent and helps reduce results which may get cut off.
Also, removing scene prefix before sending to arr as it seems to help.
> enhancement(search): remove year from series

- src/constants.ts
for certain badly named releases without codec but containing media types, prefiltering can match as an arr directory in error and exclude it from searching
this is not so much a problem with current releases, but when DVD was a thing the naming schemes were less commonly as consistent as they are today
> fix(regex/arr-dir): adds dvd as exempt keyword for arr-dir

- src/config.template.cjs
- src/configuration.ts
in windows, permissions check using accessSync in appDir() fails when the directory does not exist, have no received reports of this on linux but potentially could apply to it as well.
for users installing v6 fresh, when there is no config path in the appDir accessSync will throw erroneously failing to launch and generate any config directory.
this PR addresses this by checking if a path exists before running accessSync() on it. enabling the config path to be made if it does not exist rather than throw and terminate
fixes #766
> fix(startup/perm): check config_dir exists before permissions check

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/Transmission.ts
- src/constants.ts
- src/preFilter.ts
- src/utils.ts
this PR adds a new array for file extensions found on Blu-ray and DVD disc images (excluding single image files - iso/img/etc) and adds a case to the switch in getMediaType for unparsable titles/folders that contain these to be identified as the VIDEO mediaType
in addition, all video discs will be rechecked and paused due to inconsistencies possible. resolving these will require manual user intervention if a conflict exists - the invalid files will need to be deleted manually to break links - and then resumed. this will otherwise overwrite the files and break the searchee's torrent.
> update(mediatype/video): support for identifying mediatype of video disc images

- .idea/.gitignore
- src/preFilter.ts
this PR validates that the folders we exclude for "arr movie/series folder" are video. 
this prevents poorly named non-video torrents/data from being included in this exclusion erroneously
- using 0.02
> fix(prefilter): add check for non-video ratio in arr dir check

- .idea/dictionaries/zak.xml
- src/clients/QBittorrent.ts
Sometimes qbit will throw a terminate error on the connection but the torrent is often still injected. Instead of immediately returning injection failure, run the confirmation check first.
> fix(qbit/inject): catch terminate connection error and confirm if in client

- src/decide.ts
- src/logger.ts
Some trackers have a *really* unique guids. The same torrent can have different guids each corresponding to an alternate title. Fortunately, this guid contains the torrent id so we can fuzzy match against that to grab cached torrents.
Currently, we can have 4 snatches for the same torrent from a single searchee.
> enhancement(decide/cache): use fuzzy lookups for certain guids

- src/preFilter.ts
git blame covid-19
i put the prefilter nonvideoratio logic in the wrong area.
> fix(prefilter/logic): misplaced logic in arr directory detection

- src/action.ts
- src/arr.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/configSchema.ts
- src/constants.ts
- src/decide.ts
- src/inject.ts
- src/jobs.ts
- src/logger.ts
- src/parseTorrent.ts
- src/pipeline.ts
- src/pushNotifier.ts
- src/runtimeConfig.ts
- src/searchee.ts
- src/server.ts
- src/startup.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
[Calibre](https://calibre-ebook.com/) libraries (a popular ebooks manager) can append an index ID to the end of folder names, this PR removes that index if it is a databased match.
To accomplish this the query creation function now accepts a searchee rather than a stripped searchee title. This arg was changed elsewhere to accommodate this change for the ebook searchee check.
There is a debug function (unused) that currently will not work without some modifications, I've `ts-expect-error`'d it to prevent it without removing anything.
https://regex101.com/r/xUPDfI/1
> fix(torznab/ebook): filter calibre library index from tail of data-based search titles

- src/torznab.ts
cleanTitle removes the parenthesis i regex'd - so the replace needs to be on the stem before cleaning the title
> hotfix(search/books): parse calibre index on data searches before cleaning title

- .idea/dictionaries/mmgoodnow.xml
- src/arr.ts
- src/cmd.ts
- src/configSchema.ts
- src/indexers.ts
- src/preFilter.ts
- src/torznab.ts
This PR consolidates all of the `JSON.parse` code we were doing for some indexer columns (cat_caps, movie_id_caps, tv_id_caps) into one place. From now on, all database calls for the `indexers` table should do so by calling functions in `indexers.ts`. We can add functions to `indexers.ts` as necessary to accomplish this.
- **define caps more rigorously**
- **use hydrated indexer objects everywhere**
- **consolidate field selection**
- **move last db call into indexers.ts**
> deserialize indexer objects

- src/arr.ts
- src/clients/Deluge.ts
- src/configSchema.ts
- src/indexers.ts
- src/logger.ts
- src/migrations/07-limits.ts
- src/migrations/migrations.ts
- src/pipeline.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
If the `lastRun` for the rss job is more than `rssCadence + ms("1 minute")`, will page back until it's caught up or a maximum of 12 pages. Each rss request has a delay of 5 minute. Will detect if an indexer does not support pagination by comparing the candidates to the previous "page".
This should cover at least 3 hours to a few days depending on how many results the tracker returns each time and frequency of uploads. But unfortunately, it seems quite a few indexers don't support this. In that scenario it will only cost a single extra rss query regardless of how long `cross-seed` was down for.
Added a migration as we are now using indexer limits for rss scan.
> enhancement(rss): support pagination for rss if gap longer than rssCadence

- src/server.ts
when an invalid search request (bad infohash or inaccessible path) is provided, we return an error stating as much but did not report the search request itself.
this should be reported for debugging/troubleshooting
since neither the infohash or the path is valid, sanitizing this output is not necessary
> fix(logging/webhook): log request before error in invalid webhook

- src/db.ts
updates knex import in db.ts
knex does not have a default export, so importing it without destructuring can cause `vitest` to fail to resolve the deps (e.g. on a branch I was working on for a future PR) 
once the dep graph for vitest includes db.ts - it will always fail until the import is fixed
> fix(dep/knex): fixed failing tests on knex import

- src/constants.ts
- src/db.ts
- src/decide.ts
- src/searchee.ts
When a group is missing from a release name, it is possible that a hyphen in the release name is determined to be a group delimiter erroneously. This can result in wrongly assuming that, for example, after the DL until the end of the release name if WEB-DL is present and no group exists on the release name is a valid group to use for comparison.
This PR creates a function that parses out the release group normally, and then checks for whether a new regex (`BAD_GROUP_PARSE_REGEX`) matches.
`BAD_GROUP_PARSE_REGEX` contains a variety of format tagging for audio and media formats, in addition to a few delimiters and other terms I found to be regularly present to ensure that, in the test cases I had, the entire suspected "group" was captured.
If `BAD_GROUP_PARSE_REGEX` matches, then the …
>  update(regex/groups): check for improperly identified groups when group is missing

- src/utils.ts
`abc-...` the `...` would match as release group so we should remove the `abc-` scene prefix first.
Should we also add restrictions to release group?
> fix(utils/parsing): strip scene title before release group

- src/db.ts
tests were failing, so in order to fix them changed the import method due to some complications with default exports.
this broke knex.
we have to do some weird stuff to get around this, but it should be fine.
> hotfix(deps/knex): bad import for failing tests

- package-lock.json
- package.json
- src/torrent.ts
- tsconfig.json
fixes #411 by reading the entire contents of the `torrent` table into memory, then doing a set difference to determine which entries in the DB can be pruned. 
Also updated TS and knex due to some type issues I was having.
> Use JS comparison to prune indexed torrents

- .gitignore
- src/clients/RTorrent.ts
- src/configSchema.ts
- when constructing the `libtorrent_resume` tree, skip files that don't exist
- use `priority: 1` to set priority to Normal (it's only for files that already exist so it's somewhat moot)
- resolve relative download dirs to absolute before sending them to rTorrent
> Fix rTorrent injection for partial matches

- src/cmd.ts
- src/preFilter.ts
- src/torznab.ts
`cross-seed clear-cache` will now also clear the search timestamps which will re-search the users library. To prevent all searches happening at once, they are each delayed randomly for up to `30 days`. `first_searched` is set to when the first new search will occur and `last_searched` starts at `nMsAgo(excludeRecentSearch ?? 0)`.
Users may need to use this command upon migrating to v6 or if they were on v6 pre-release due to incremental improvements. They should only need to do this once, unless we make significant improvements to `cross-seed` (unlikely).
> enhancement(clear-cache): also clear search timestamps

- src/config.template.cjs
- src/server.ts
- src/torznab.ts
When a search is performed via the `/api/webhook` endpoint with no configured indexers, this throws an error. Since this workflow is potentially useful for autobrr-dependent instances and the error is somewhat vague, after discussions we decided to demote this to a simple warning.
In the case of no indexers with a webhook search, it will now warn, log verbosely the request, and return a 503 (service unavailable).
This leaves the opportunity for misconfigurations (albeit rare with Zod) or potentially adding this return to "all failing indexers", etc, to be warned of the issue more concisely so it can be handled, while also not leading users to think that there is a larger problem plaguing their instance.
Thoughts on messaging and status code returned by the API are needed. 
500, 501, and …
> update(logging/webhook): warn on no indexers and verbose log the request

- .idea/dictionaries/mmgoodnow.xml
- src/jobs.ts
I noticed that an empty torznab array doesn't give any indication to the user that it's empty if you are using cross-seed for the first time. I removed this `torznab.length` check before installing the `search` and `rss` jobs so that the user gets feedback about `torznab` being empty. @buroa this undoes part of #627 but you can just set `searchCadence` and `rssCadence` to null to achieve the same thing.
> run jobs with empty torznab so the user sees feedback

- src/pipeline.ts
- src/torznab.ts
Indexers sometimes have a delay before publishing new torrents to their RSS feed.
Cross-seed only looks for new torrents published after the previous RSS run, and with the delay some releases might end up published in the past to the previous run and missed by Cross-seed.
This PR allows cross-seed to look for releases up to 5 minuntes prior to the previous RSS run, thus mitigating the delay of publishing.
Cross-seed might end up seing some releases twice, but as the processing is very fast this should not add much overhead.
I've been runing this for 8 hours without issus at the opening of this PR.
<hr>
note: conversation on discord can be found [here](https://discord.com/channels/880949701845872672/1301568641329926204) //zak
> enhancement(rss): mitigate RSS publishing lag with offset

- src/config.template.cjs
This will satisfy people's instant gratification mindsets a little better and it seems like trackers are okay with pretty much anything as long as the `delay` is reasonable. This is worse for the feast vs famine use of API issue as described in https://github.com/cross-seed/cross-seed/issues/432, but users looking to resolve that can just set it lower.
> Increase default searchLimit to 400

- src/server.ts
There is no endpoint for checking health via the API.
This PR introduces a `/api/status` endpoint that returns "200 OK" and does not log to the terminal.
Health checks that are performed frequently would not need to be logged, as they are always going to succeed assuming cross-seed is running anyway, and would just be "spam".
Currently requires API auth same as any other API call.
Applications that could utilize this are things like uptimekuma and notifarr.
This could also be expanded in the future to return any current jobs down the road if that was something we desired to do (such as "performing search" type of status). Currently it just acts as a ping endpoint to check if cross-seed is operational.
> add(api/status): introduce status endpoint for health checks

- src/action.ts
- src/arr.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/configSchema.ts
- src/constants.ts
- src/inject.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
- tests/utils.test.ts
This should make the feature PRs easier to review. Most of what was extracted won't have any immediate effect but will be necessary for the upcoming features.
Client type and `getClient()` being optional allows blocklisting using torrent data if available. Type allows handling qbit specifically since we read the data from fastresume usually.
`getAllTorrents()` is used to get the blocklisting information from the clients. Also updated `checkOriginalTorrent()` for rTorrent for this purpose.
`getAllDownloadDirs()` is to find the absolute file path of each episode torrent for ensemble. This prevents individual requests for each torrent.
`getLargestFile()` and `getNewestFileAge()` are for getting the episode file from a searchee and controlling when to search for ensemble.
Added binary for …
> enhancement(general): extract non feature functionality for upcoming features

- src/config.template.cjs
updates language used in the config template descriptions to more accurately explain when the option is relevant, specifically when using the term "torrent" to mean any searches.
also updated the tagging behavior when using linking in the duplicateCategories option, as this has come up previously too as ambiguous if linking is disabled.
fixes @bakerboy448 
oh wait cant fix bakerboy :P
> update(config-template): clarify usage across data and torrent for option descriptions

- src/migrations/08-rss.ts
- src/migrations/migrations.ts
- src/pipeline.ts
- src/torznab.ts
Stores the last seen guid per indexer in a new `rss` table. This should handle all previous edge cases of rss processing.
> enhancement(rss): better pagination using last seen candidates

- src/decide.ts
- src/inject.ts
- src/pipeline.ts
- src/torrent.ts
- src/torznab.ts
The previous method for getting the infohash was extremely slow. It took `500ms` to retrieve per candidate for which there could be 2000. Meaning daemon mode is overloaded for 16 minutes.
Now the decision table is only queried once and stored in a hashmap for instant lookups. These same 2000 candidates are now processed in 15s instead of the 16 minutes currently. The `fuzzyGuidLookup` would take 1s if it was relevant so that is also using the hashmap for instant lookups as well.
After making an assessment, we will add the `guid: infoHash` to the map. This is to prevent duplicate snatches for the next candidate check if `fuzzyGuidLookup` is needed, and for the next searchee to use in the case of rss/announce.
Now checking the link instead of just the guid. Announce only uses the link (no …
> fix(decide/cache): optimize query for using cached torrents

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/configSchema.ts
- src/diff.ts
- src/pipeline.ts
- src/searchee.ts
- src/startup.ts
- src/torrent.ts
This is better than simply checking for the presence of a single .torrent file. Users have frequently set `torrentDir` to the directory their client copies .torrent files to, instead of the one that mirrors the client state.
I also added the check for searchee blocklist before testing the save path. It's still only being logged until the new blocklist features are included.
> enhancement(torrentDir): verify contents against client

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/inject.ts
- src/runtimeConfig.ts
This offers `cross-seed` the highly requested ability to resume partial matches without user intervention. Also, we will now recheck and resume all non torrent based searchees as well since we can't tell if a data/virtual searchee is completed.
Readded the skipRecheck option since we can now resume torrents after rechecking.
The maximum that we will resume is `50MB` remaining. This was chosen as it should resume all normal partial matches while never resuming those from ensemble and for the `inject-saved-torrents` feature to only download missing data once between partial matches on different trackers. We do not need to check for fuzzy ratio as the decide stage already has for partial matches.
In the worst case, say a user has 100 partial matches for a single tracker, the maximum download …
> feat(action/inject): resume injections below size threshold and readd skipRecheck

- src/configSchema.ts
using save should allow for `linkDir` to not be set, as it doesn't link.
this also prevents users who use things like autotorrent, or manually add the torrents and links (if needed) from using risky or partial.
there is no reason to require a setting that is not used for `matchMode`.
> fix(zod/linkdir): do not require linkdir for risky or partial when action is save

- src/clients/TorrentClient.ts
- src/config.template.cjs
- src/configSchema.ts
- src/constants.ts
- src/decide.ts
- src/diff.ts
- src/parseTorrent.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/torrent.ts
qBittorrent strips everything from `BT_backup/abc.torrent` except for the info dict. So we need to read the tracker urls from the `BT_backup/abc.fastresume`. This is trivial since it's in the same directory. It also has every bit of information about the torrent so we read categories and tags at the same time.
All other clients use API calls to get the labels. They have fastresume like structures but aren't in torrentDir (except for rTorrent) and so would require another config option. qBittorrent will also fallback to use API in the case of `cross-seed search --torrents` as they might not be from `BT_backup`.
Labels are considered tags, since a client may support multiple in the future (transmission does). Categories and tags must match exactly while tracker urls require the host …
> enhancement(blocklist): torrent categories, tags, labels, sizes, and tracker hosts

- src/action.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/db.ts
- src/decide.ts
- src/inject.ts
- src/pipeline.ts
- src/preFilter.ts
- src/runtimeConfig.ts
- src/searchee.ts
- src/signalHandlers.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
This feature allows grabbing rss/announce and searching of seasons from individual episodes. Along with the changes in v6, this feature completes all possible matches from cross-seed aside from tweaks.
This works by introducing a new type of searchee, a virtual searchee. This is needed since the episodes are sourced from multiple torrents and folders. As such, it hash no `infoHash` or `path`. All areas of the application where these were used for logic has been updated to reflect this new possiblity. In general, this should be treated as a data based searchee if searchee.path is not need. So most checks went from `if (searchee.path)` to `if (!searchee.infoHash)` so that virtual searchees are included.
Virtual searchees also have absolute file paths instead of relative to make linking …
> feat(match): ensemble matching for episodes

- src/config.template.cjs
Fix comment to clarify that only `null` disables `seasonFromEpisodes`. Since it is set using [`fallback`](https://github.com/cross-seed/cross-seed/blob/19054f3b9424e6850c4ddc06c4fbeab091b3f488/src/cmd.ts#L195), `undefined` actually sets it to `1`.
> update(config-template): Fix comment for disabling seasonFromEpisodes

- src/action.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/pipeline.ts
- src/searchee.ts
- src/startup.ts
- src/torrent.ts
In case of `seasonFromEpisodes: undefined` (or missing from config), it will now default to `null`, preventing validation errors. Even though a default of `1` is fine for most users, the error has confused others.
Will now warn if using `action: save` due to the complexity of these matches.
Ensemble requires clients to be connectable if torrentDir is enabled, this will now be checked during validation.
> fix(config/seasonFromEpisodes): better validation

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/config.template.cjs
- src/configSchema.ts
- src/constants.ts
- src/parseTorrent.ts
- src/preFilter.ts
- src/server.ts
Labels were previously associated with the `tag:` prefix in blocklist, the rationale was that there might be a time when labels are able to be applied in more than one and the type was a string.
This will not be the case, Deluge uses labels in the same way that qBit does, for save path, bandwidth and queue, etc. Multiple labels will not ever be a concern.
This changes labels to category. Tags are assigned empty array, since no tags exist in Deluge.
> update(blocklist/deluge): change labels to be category rather than tag

- src/action.ts
- src/clients/TorrentClient.ts
- src/config.template.cjs
- src/inject.ts
This is primarily for racing ensemble from announce.
With the new `searchee.mtimeMs` for data/ensemble searchees, we should be able to tell if complete in most scenarios. The only exception is for stalled torrents, which should be rare. The inject job already handles and sometimes inject stalled torrents anyways.
Will always save data/ensemble .torrent files anyways in case there is an issue, the inject job will automatically resolve it.
> enhancement(inject): skip recheck for complete data/ensemble

- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/dataFiles.ts
- src/db.ts
- src/decide.ts
- src/logger.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/server.ts
- src/torrent.ts
- src/torznab.ts
This uses `fs.watcher`, which recently supported recursive watch all on platforms in Node v19. This detects new/removed files and modified files, which is all we need. We do not run it all the time, as soon as a change is detected we cancel it for that dataDir. Then on next rss/announce we will reindex only the dataDirs with a change and restart the watcher.
The indexing is stored in memDB, essentially the same as the torrents table for lookup. But we parse the title instead of name so that media season folders and others are meaningful. As with ensemble, memDB makes the lookups much quicker and is only a couple megabytes (when on disk) for 20k entries. Also adds a few seconds for indexing at startup.
Recommended `maxDataDepth` is 3 if using on media libraries. This is so that …
> enhancement(dataDirs): support rss/announce matching

- src/server.ts
This corrects bad logic on a throw which allows for falsey path (empty string) to not return 400.
Throws now on:
path string is falsy (e.g., '', null, or undefined)
file or directory specified does not exist
> fix(zod/webhook): corrects bad logic on path validation in webhook api calls

- src/action.ts
- src/clients/TorrentClient.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/inject.ts
- src/pipeline.ts
- src/runtimeConfig.ts
- src/searchee.ts
- src/startup.ts
- src/utils.ts
fixes #625 
`linkDir` is converted to `linkDirs: [linkDir]`.
We choose a linkDir by testing if stat.dev if between source path and any linkDir is the same. Hardlink requires this to have a match but symlink will only display and warning and use `linkDirs[0]`.
The only possible issue is with `seasonFromEpisodes`, these could be sourced from multiple drives. The ones that are will be logged as failures before attempting to link.
> enhancement(action/linking): support multiple linkDirs

- src/startup.ts
Since the addition of the inject job, we should always verify `outputDir`. Considering `outputDir` is always required, this should only error for users who have it misconfigured.
> fix(outputDir): always verify ouputDir

- src/server.ts
- src/torznab.ts
If a user has trailing white space in the Prowlarr indexer names, `flatLinking: false` will preserve this when linking but qBittorrent trims the savePath when being injected.
> fix(action/linking): trim tracker to match qbit behavior

- src/decide.ts
- src/jobs.ts
- src/utils.ts
The goal is to prevent matching guid to a cached torrent from another tracker if the infoHash is the same. This can cause a torrent to be injected with the wrong save path with `flatLinking: false` and incorrect tracker logging. The torrents from these two trackers would not be able to coexist in client regardless so first come first served is fine.
This prevents caching the guid in the db if we try to snatch but the infoHash already exists in the cache. It already won't overwrite the existing file and only update the last access time. Now it also won't cache this result in the database. This should only happen in these scenarios:
- This bug
- If the user has deleted the config.db without deleting the torrent_cache
- Any more trackers that benefit from fuzzy lookups that we haven't …
> fix(decide/cache): don't update db if snatch already exists

- src/constants.ts
- src/decide.ts
I've readded the repack check which was removed in #707 due to decision cache. Since we are no longer caching decisions without snatches, this no longer applies.
Previously, this would only fail if the user was in safe mode, it can now fail in all modes. It's also no longer checking the `ARR_PROPER_REGEX` as this is a subset of the main regex. The searchee and candidate must now share the same version or both be missing.
This will increase the false negatives as some places don't correctly tag repack status, but a few repacks have been seen with the same size. Since repacks are rare, this should be a fine tradeoff for safety.
> enhancement(decide): check release version

- src/torznab.ts
In #668, the timestamps filter in torznab was filtering Promises meaning it always returned true. After ensemble was developed `getSearcheeNewestFileAge` became async and I incorrectly kept using filter instead of filterAsync when refactoring. This has been largely unnoticeable due to the main filtering happening during preFilter.
> fix(torznab): properly exclude by timestamps per indexer

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/dataFiles.ts
- src/db.ts
- src/inject.ts
- src/parseTorrent.ts
- src/pipeline.ts
- src/preFilter.ts
- src/runtimeConfig.ts
- src/searchee.ts
- src/server.ts
- src/startup.ts
- src/torrent.ts
- src/utils.ts
One thing of note is moving the indexing to as early as possible for rss/webhook/announce. This is to better take advantage of preventing simultaneous indexing.
> extract boilerplate for useClientTorrents

- src/action.ts
- src/constants.ts
Fixes: #421
`reflink`does nothing for partial matches which the original issue seemed to misunderstand. The only benefit to cross-seed (aside from user preference), is better handling the rare corrupted cross seeds. The main downside of reflink is the delayed performance impact to when writes are requested rather than on creation, which is irrelevant in the context of seeding.
With the testing at startup and checking for the same `stat.dev` (#835, #861), we can add `reflink` without any unintented side effects while checking if the user system supports it. There could be an argument made to not require the same `stat.dev` but then this opens up `cross-seed` to straight up copying the data. I think we should wait until a valid use case is presented then add it as a new `LinkType` that uses …
> enhancement(linkType): support reflink

- src/configSchema.ts
- src/dataFiles.ts
- src/pipeline.ts
- src/runtimeConfig.ts
- src/server.ts
- src/startup.ts
- src/utils.ts
`fs.watch` recursively creates watchers on linux. This limit can be reached depending on user configuration. For docker containers, it's simply read from the host system. This will warn users if their limit could be an issue with the amount of files in dataDirs to watch.
Also converting nullish dataDirs into an empty array to match other config options.
> logging(dataDirs): warn users with low max watches

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/config.template.cjs
- src/configSchema.ts
- src/dataFiles.ts
- src/inject.ts
- src/parseTorrent.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/torrent.ts
- src/utils.ts
Fixes: #365 
Added `useClientTorrents` which replaces `torrentDir`. They cannot both be enabled.
There is now a new type of Searchee, `SearcheeClient`. This is like `SearcheeWithInfoHash`, but has a new field `savePath` which makes linking much easier.
This change means that we now support renames in client or any modification a user can do. Right before linking, we refresh the searchee to catch any renames as the db only updates on added/deleted. All searchees are also refreshed at the start of each search cadence.
Indexing torrents and data now happens asynchronously. There is also now prevention of multiple concurrent indexes to not overload the client/disk. If an index is in progress, announce/rss/webhoook will simply wait on its completion without triggering a new one.
I think we …
> feat(clients): option to use APIs instead of torrentDir

- src/decide.ts
- src/pipeline.ts
- src/preFilter.ts
- src/runtimeConfig.ts
- src/server.ts
- src/torznab.ts
- src/utils.ts
Fixes #869
This `getRuntimeConfig()` now takes `configOverride: Partial<RuntimeConfig> = {}` to override config values for that call. This is used by these webhook params.
The primary use for `webhook` is to immediately trigger a search on download completion. Any other automation should be handled by `searchCadence`. As such, we should default to config options but allow overwriting a few notable ones.
The docs should also be updated with overriding `includeSingleEpisodes` being a valid alternative for download completion as they are unlikely to have been trumped by a season pack.
`curl -XPOST <BASE_URL>/api/webhook?apikey=<API_KEY> -d "infoHash=%I" -d "includeSingleEpisodes=true"`
Additionally, I think `webhook` should ignore torrents with the `cross-seed` tag by default, in service of …
> enhancement(webhook): ability to override certain config options

- src/decide.ts
We can't rely on REPACK/PROPER consistency between trackers and with data. The check is reduced to if it's a re-release rather than a specific re-release.
> enhancement(decide): treat repack and proper the same

- src/clients/TorrentClient.ts
- src/configSchema.ts
- src/torrent.ts
Fixes #890
The refactoring of how torrents are indexed broke this use case since it wasn't explicitly defined. I verified this configuration and there should be no issues.
I also added an extra config check for `action: save` with linkDirs defined.
> fix(torrentDir): support torrentDir without client if action save

- src/cache.ts
- src/cmd.ts
- src/decide.ts
- src/parseTorrent.ts
If a user changes their announce key or a tracker url changes, the `torrent_cache` needs to be updated. This can be done using tools like `sed`, but this is not cross-platform and a bit more complicated for users.
> feat(cmd): add cmd to update torrent_cache trackers

- src/preFilter.ts
- src/utils.ts
These can never be the arr dirs that we are trying to filter against. This will only happen if the user has non-standard naming for their arrs.
The other time this can happen is if it's trying to search `Specials`, so now I added an explicit check for this. `Specials` will usually get parsed into `Show S0` due to the episode files in the folder.
> enhancement(preFIlter): exclude episode/season from arr directory detection

- src/configuration.ts
- src/logger.ts
due to db.ts being read and the following line referencing appDir during gen-config runs
https://github.com/cross-seed/cross-seed/blob/master/src/db.ts#L8-L9
the path may be referenced before it exists...causing better-sqlite to freak out and fail.
when receiving an ENOENT during startup and appDir() execution, simply create the path, as we will undoubtedly need it anyway.
rename the createAppDir() function appropriately as well, and document this behavior in jsdocs.
probably a better way to handle startup long term, but wanted to get a solution available that prevents new users from facing failures on step 1.
- consolidated discord thread: [Discord](https://discord.com/channels/880949701845872672/1335949251645280306/1335949251645280306)
> fix(db/startup): prevent invalid pathing returns on new install referencing the db/appDir

- src/action.ts
- src/searchee.ts
- src/torrent.ts
This is to better support renames in client for `useClientTorrents`. For .torrent and data based searchees, they are equivalent by definition. This is likely why `searchee.name` was being used to calculate `sourceRoot` all this time.
In qBittorrent, you can rename the torrent itself or its files. Renaming the files is currently handled by `useClientTorrents`, but renaming the torrent is not.
This is fixed by using the root folder from `files[0].path` instead of `searchee.name` for `sourceRoot` to cover the cases where it differs for API based searchees. This is what we use when linking so it's also conceptually more correct.
> fix(searchee): use `file.path` instead of `searchee.name` for sourceRoot

- src/clients/RTorrent.ts
- src/utils.ts
I believe this was discussed in the review and it ended being necessary.
> fix(rtorrent): batch requests for getClientSearchees

- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/constants.ts
- src/decide.ts
- src/inject.ts
This updates the names for `matchMode` to be less misleading. The new ones are `strict` `flexible` `partial`. This better conveys that these options are equally safe as many users took `safe` and `risky` too literally.
I also think we should update the config template to `matchMode: "partial"` and `seasonFromEpisodes: 0.8`. Users have long asked for `optimal` settings and this should be close to it for most. If we are assuming that users will be setting up linking, similar to how the current options assume a client will be configured, we should start with these options. If a user cannot use linking or they do not want to, the options become opt-out for new users.
I think we have enough evidence that these options bring the user more matches with no real increases in risk. Though I …
> update(matchMode): use "strict" and "flexible" instead of "safe" and "risky"

- src/searchee.ts
This will allow more pre-snatch rejections during decide for parsed titles (e.g. sonarr season folders). Resolution, source, and group needs to be unanimous. Release version only requires a single file.
Since the release version only requires a single file, there could be false positives on sonarr libraries where the episode title contains `Repack|Proper`. This also happens with titles for a movie/show, but is more likely here due to there being more episodes.
> enhancement(searchee): use meta info in parsed titles

- src/cmd.ts
- src/jobs.ts
- src/pipeline.ts
- src/preFilter.ts
- src/searchee.ts
- src/server.ts
- src/startup.ts
This is from speaking with @zakkarry about `cross-seed search --no-exclude...`. Since we can't run two instances of `cross-seed` at the same time (commands that affect the db), triggering the jobs in daemon mode makes sense.
This follows up on the webhook params on overriding certain config options for this request, only `excludeOlder` and `excludeRecentSearch`.
When a job is manually triggered, it will run now and it will be scheduled at `cadence * 2` in the future. So the next search would be in `2 days` instead of `1 day`. It will also prevent triggering the job until we are within the cadence of the job. So the user would only be able to trigger again once the scheduled run is `1 day` away.
Checks are done to see if the job is available to be ran (e.g. no `searchCadence`) and if it's …
> feat(api): add endpoint to trigger jobs

- src/action.ts
- src/arr.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/dataFiles.ts
- src/decide.ts
- src/inject.ts
- src/pipeline.ts
- src/pushNotifier.ts
- src/searchee.ts
- src/server.ts
- src/startup.ts
- src/torznab.ts
This improves the logs a bit by consistently using `e.message` in the error logs for a quick summary.
I noticed some issues with consuming response bodies in arr.ts. So I added some clones to which seems to have solved the issue.
Also checking if parent path exists before linking to avoid any unnecessary errors.
> logging(errors): display e.message

- src/action.ts
- src/utils.ts
If `stat.dev` is not available, `getLinkDir` will try linking to each `linkDir` and return the first successful one.
> fix(action): fallback to alt method if no stat.dev to determine linkDir

- src/decide.ts
- src/pipeline.ts
- src/torrent.ts
- src/torznab.ts
The core issue is that snatches can fail due to transient errors. This usually is from `announce` and `rss` due to the torrents being fresh, but it also happens with `search` and `webhook`. I find that `4` retries is a good number with a minute between each. Since snatches can now be much longer, I also updated `assessCandidates` to run async per indexer.
This comes one step short of addressing #375. Currently, `rss`, `search`, and `webhook` all respect `Retry-After` since they query the indexer first using `getEnabledIndexers()`. We can try also parsing `Retry-After` and updating the db from snatches, however the urls differ slightly from the db and would require some extra work. If we needed to rate limit an indexer, this would save at most 1 request but most of the time it will be 0. …
> enhancement(snatch): retry snatches

- src/action.ts
- src/clients/QBittorrent.ts
- src/clients/TorrentClient.ts
- src/inject.ts
- src/searchee.ts
- src/torrent.ts
- src/utils.ts
This adds support for the `Don't create subfolder` option in qbit which means `cross-seed` can now handle all modifications that a user can do. This is only supported with `useClientTorrents`, doing this for `torrentDir` would require a large refactor of how we link which is why it hasn't be supported all this time. This option removes the root folder, so episodes are stored directly into the `savePath`, instead of `savePath/Show.S01`. 
This builds on #908 by now completely getting rid of `sourceRoot`, it was only used to test if the file exists which is still being performed. We now use `savePath/files[x].path` everywhere to get the absolute paths of torrents.
I also added two more validation checks that moves implicit runtime errors to startup:
- Require v4.3.1+ (released 11/25/2020) …
> enhancement(qbit): support `Don't create subfolder`

- src/constants.ts
- src/dataFiles.ts
- src/db.ts
- src/pipeline.ts
- src/searchee.ts
- src/torrent.ts
- src/utils.ts
Some trackers use a title of `TitleA AKA TitleB`, this splits by AKA and also performs the reverse lookup using all 3. This required supporting multiple keys for lookup for all media types, similar to anime.
I've also noticed some puts it after the title as "metadata", like `TitleA 2025 AKA TitleB`, these will not be supported.
> enhancement(reverselookup): handle AKA in titles

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/dataFiles.ts
- src/db.ts
- src/logger.ts
- src/preFilter.ts
- src/pushNotifier.ts
- src/runtimeConfig.ts
- src/searchee.ts
- src/startup.ts
- src/torrent.ts
- src/utils.ts
Only a single client is supported on this branch.
The goal for this feature is to source searchees from multiple clients and cross seed them to their respective clients. cross seeding from one client to another is not supported. Injections will only happen in a single client, the already exists checks looks at all clients.
The client config options have all been deprecated and `torrentClients: []` is used instead. Each url must be prefixed by it's client type similar to blockList. This allows the user to define a `clientPriority` which affects which client is chosen when source torrents are duplicated/ambiguous.
The `URL(url).host` is used to distinguish between clients, duplicates are not allowed. This is added to `SearcheeClient`. Logging for the clients now includes this to distinguish …
> framework for multiple client support

- src/configSchema.ts
fixes #928 
Just like with he exclude options, when using `--no` command returns a false (boolean) - which does not conform to Zod. We have to transform this to null in order for it to meet 'nullish' and operate properly in cross-seed
> fix(seasonFromEpisodes/zod): fix no-season-from-episodes triggering zod due to typecheck

- src/configSchema.ts
- src/decide.ts
Due to the way autobrr retries announces, it could send another one even before the 202 code is reported by `cross-seed`. Bumping this to `5 minutes` for announce should help.
`search`, `webhook`, and `rss` cannot have concurrent snatch attempts themselves. Two different jobs can have concurrent snatches for the same tracker, but that's extremely unlikely to happen at any scale unlike announce. Also, these assessments are not completely isolated as each announce is. The `search` job might perform 10,000+ assessments over the course of it's entire run.
Also added the ability to override the deluge restrict with the `DEV` env variable like other options.
> update(snatch): 5 minute retry for announces

- src/configSchema.ts
Using a `maxDataDepth` of more than 3 cross-seed will issue an error. This is misleading, as there are certain rare edge-case folder structures that can be valid and necessitate a depth greater than 3.
This reduces the error to a warning.
> update(zod/maxdatadepth): classify greater than 3 depth as warning

- src/cmd.ts
- src/diff.ts
Creating searchees can fail if certain criteria aren't met.
> fix(cmd): use metafile directly for diff and tree

- src/action.ts
- src/clients/Deluge.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/configSchema.ts
- src/inject.ts
- src/pipeline.ts
- src/searchee.ts
- src/startup.ts
- src/torrent.ts
- src/utils.ts
fixes #223 
This adds support for `useClientTorrents: true`, `dataDirs` requires a different process and will be added later. Supporting `torrentDir` will add a great deal of complexity and may not be needed. We should avoid doing this unless necessary.
Most areas of the application now uses `getClients()` and performs the operation across all clients. `getClient(searchee)` is only used during linking to determine which client to inject to. If there is only a single client, it's always returned to preserve existing functionality.
Searchees are always sourced from all clients then later sorted `byClientPriority` to ensure consistent injection preferences. Though if the injection fails for one client, it could be injected into another. Webhook infoHash lookup returns torrents from all …
> feat(clients): support multiple clients with useClientTorrents

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/configSchema.ts
- src/inject.ts
- src/pipeline.ts
Required a large refactoring of `action.ts` and which affected `inject.ts` and the clients. Mainly was just about moving lots of the work into their own separate functions to get more flexibility. Also took more advantage of union types to help specify what's possible in certain conditions.
All the new functionality is in `getClientAndDestinationDir()` with the integration in `performActionsWithoutMutex()`. The changes in `inject.ts` are simply due to the new function signatures in `action.ts`. The changes for the clients are to standardize the handling of `TORRENT_NOT_COMPLETE` and using `destinationDir` instead of `path` for the `client.inject()` argument.
As before, a single client has the same behavior. `dataDirs` and ensemble `dataDirs` choose a client by testing linking to the …
> feat(clients): support multiple clients with dataDirs

- src/action.ts
- src/inject.ts
- src/pipeline.ts
This was previously only supported from the inject job, it is now supported from `search`, `rss`, and `announce`. The main change was moving the check from the inject job to the action stage. If the torrent already existed and new files were linked, we will recheck and resume.
The main benefit is to prevent unnecessary downloads when another searchee has the file. For example, the user has two searchees, one with `.nfo` and another with `.srt` and the candidate needs both. It partly addresses this [FAQ](https://www.cross-seed.org/docs/basics/faq-troubleshooting#my-partial-matches-from-related-searches-are-missing-the-same-data-how-can-i-only-download-it-once).
Since the searchees from `search` are already grouped by similarity for caching, no change is needed in the process. However for …
> enhancement(inject): link files from multiple searchees

- src/searchee.ts
If the title of the media contains a hyphen, there is a chance that it matches as the release group. This would only be in cases of parsed titles for ensemble `Re:ZERO -Starting Life in Another World.S3`.
This checks if the release group parsed from the title is a substring of the one parsed from the entire release.
> fix(regex/group): prevent group matches from titles

- src/constants.ts
Covers parsing titles should as `'9-1-1.S01` into `1-1`.
> fix(regex): cover edgecases in scene title parsing

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
fixes #926
This allows a user to define clients to use only to source cross seeds from, but not to inject into. This better alternative to the [3rd use case](https://www.cross-seed.org/docs/tutorials/data-based-matching#general-usage-for-datadirs) for dataDirs. If the user is using `action: "inject"`, at least one client must be `non-readonly`.
Users will denote `readonly` status by:
`torrentClients: ["deluge:http://:password@localhost:8112/json", "qbittorrent:readonly:http://username:password@localhost:8080"]`
where all cross seeds would be injected into deluge but can also match from qbit.
The only change required is during the action stage. We simply filter out any clients that are `readonly` from being selected, while still keeping them for checking existing.
> feat(torrentClients): support clients as readonly

- src/action.ts
- src/config.template.cjs
- src/utils.ts
If `infoHash` is present in the `inject()` function, the current logic expects it to be in client. By treating it as data-based, we only lose `duplicateCategories` functionality. But this is not a big deal since different clients uses `categories`, `tags`, and `labels` differently. Rewriting the `inject()` functions to preserve this is not worth it.
> fix(torrentClients): treat readonly searchees as data-based

- src/jobs.ts
- src/server.ts
This improves the inject job workflow as we often want to run after a download is completed in client:
1. The torrent that just completed had saved cross seeds due to `TORRENT_NOT_COMPLETE`. The inject job now triggers within the next minute to inject these earlier.
2. The torrent that just finished was a partial match. This could have downloaded new files for other partials matches, mainly for this [FAQ entry](https://www.cross-seed.org/docs/basics/faq-troubleshooting#my-partial-matches-from-related-searches-are-missing-the-same-data-how-can-i-only-download-it-once)
The next run time will be at its normal cadence unlike with the `/job` api.
> enhancement(job/inject): trigger inject job on webhook completion

- src/action.ts
Creating a temp file for testing linking is used if we can't find any valid file to link with (the extensions we support) and `stat.dev` isn't available. If we fail to create a tempfile, we log and error but do not fail validation.
1. Check if we have write access to create a temp file. This can happen if we are testing `dataDirs` as we only require read permissions for that.
2. Verify tempfile was created before trying to use it, the write can silently fail it seems.
> fix(testLinking): add more checks around creating temp file

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/config.template.cjs
- src/dataFiles.ts
- src/db.ts
- src/decide.ts
- src/jobs.ts
- src/migrations/09-clientAndDataSearchees.ts
- src/migrations/migrations.ts
- src/pipeline.ts
- src/searchee.ts
- src/startup.ts
- src/torrent.ts
fixes #910
1. New migration for `client_searchees`, `data`, and `ensemble` tables.
2. Update the `cleanup` job to also handle these tables to ensure `client_searchees` are refreshed (catch renames, new categories, tags, trackers, etc), and that `data` and `ensemble` gets pruned for paths that no longer exists (only happens if `cross-seed` was down so files weren't being watched).
3. Upon startup, we will clear tables for the options the user has not configured. e.g. `torrent` gets cleared if no `torrentDir`, `data` is clear if no `dataDirs.length`, etc.
4. Added `cross-seed clear-client-cache` to clear the `torrent`, `client_searchees`, `data`, and `ensemble` tables. Only needed if the user doesn't want to want on the cleanup job for the refresh or if they moved to a new client with the …
> update(db): remove memDB

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/config.template.cjs
- src/configSchema.ts
- src/configuration.ts
- src/constants.ts
- src/inject.ts
- src/pushNotifier.ts
- src/runtimeConfig.ts
The behavior idea I had in mind involves excluding known non-relevant files as a second measure to check if resuming is desired. This should cover most instances where any sample or miscellaneous file commonly included in some trackers prevents resuming and provides a larger buffer to resume with.
The option to enable this behavior is `ignoreNonRelevantFilesToResume`. Defaults, if not included in the config (onboarding), to false. The previous behavior stays intact with the 50MB limit, but I'm not sure that increasing it as @ShanaryS suggests in #939 is necessary given this option's functionality, and I would contend that that is not the best or proper "total" solution for the job.
> feat(inject/ignoreFiles): ignore certain non-relevant files for resume behavior with partial matches

- src/action.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/startup.ts
- src/torrent.ts
Instead of relying only on the `cleanup` job to catch modifications, we can check most of them each time we poll the client. We will update `name`, `savePath`, `category`, and `tags`, these will essentially never be out of sync.
`files` and `trackers` will only be handled in the `cleanup` job as qbit requires different api calls for each for every torrent. This is not a problem though as trackers will pretty much never be updated and files changing doesn't affect anything aside from `matchMode: "strict"`.
Searchees are still refreshed during the action stage regardless.
> enhancement(clients): check for torrent modifications each poll

- src/jobs.ts
- src/server.ts
- src/utils.ts
Also will only delay `search` and `rss` jobs, all others can continue at their regular cadence.
> enhancement(jobs): triggered jobs run immediately

- src/cmd.ts
- src/configSchema.ts
- src/configuration.ts
- src/inject.ts
- src/runtimeConfig.ts
- src/startup.ts
Occasionally there might be torrents that are matches but fail the `cross-seed inject` fuzzy lookup. This adds a command to bypass this check if the user is confident the torrents are simply named badly.
This defaults to false (current behavior) and is only available with the `cross-seed inject` command. If a potential match was rejected due to a title mismatch, the torrent will not be deleted.
> enhancement(cmd/inject): add `--ignore-titles` to skip fuzzy matching

- .eslintrc.json
- src/action.ts
- src/arr.ts
- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/cmd.ts
- src/configSchema.ts
- src/dataFiles.ts
- src/db.ts
- src/decide.ts
- src/inject.ts
- src/jobs.ts
- src/migrations/09-clientAndDataSearchees.ts
- src/parseTorrent.ts
- src/pipeline.ts
- src/preFilter.ts
- src/pushNotifier.ts
- src/searchee.ts
- src/server.ts
- src/startup.ts
- src/torrent.ts
- src/torznab.ts
- src/utils.ts
- tests/utils.test.ts
- tsconfig.eslint.json
This ends up being a pretty large refactor. The goal is to replace all the `fs.*Sync` with their async versions as mentioned a while back by @mmgoodnow. I organized `utils.ts` and when through a lot of the async functions with `eslint` rules to clean up their usages.
1. Reorganized utils
2. Use `fs/promises` instead of `*Sync` function calls in `fs`. The exceptions are for zod schema parsing which of course is low value. It would require `parseAsync` which seems to have performance issues reported at the very least.
3. Created and used `mapAsync`, `flatMapAsync`, `reduceAsync`, `findAsync`, `everyAsync`, and `someAsync` functions in addition to the existing `filterAsync` to standardize async usage for functional pipelines.
4. Use `Uint8Array` instead of `Buffer` for saving .torrent files. …
> refactor(async): replace fs sync functions with async

- src/constants.ts
this PR adds all valid non-previously assigned video extension formats the constant for `VIDEO_EXTENSIONS` in constants.ts expanding support for more niche formats and older generation video formats
@bakerboy448 supplied the link to sonarr's extensions list which I used to expand this list https://github.com/Sonarr/Sonarr/blob/66633b9b07cf09da18809f789dc92b9c7dbf7105/src/NzbDrone.Core/MediaFiles/MediaFileExtensions.cs
some of these formats are used to identify discs and were omitted deliberately, the rest were added.
> update(video-formats): add sonarr supported valid video extensions

- src/indexers.ts
- src/migrations/10-indexerNameAudioBookCaps.ts
- src/migrations/migrations.ts
- src/pipeline.ts
- src/preFilter.ts
- src/torznab.ts
The main change is using the search caps for `EPISODE`, `SEASON` and `MOVIE` MediaTypes in `indexerDoesSupportMediaType`. A movie tracker has a single tv category of miniseries which causes `cross-seed` to search all episodes and season packs. Using the `tvsearch` caps would address this issue instead of using cats. This seems to work well with all indexers.
I added a migration for audio, music, and book search caps for completeness. They are used in addition to categories for these media types. I also added a new column for name so we can log the names. This is updated on each torznab results call to avoid using the Prowlarr and Jackett APIs.
When we are updating indexer caps (startup and job), we will log the indexer mediatypes support in verbose to make the behavior more clear.
> update(search): determine caps using search types instead of cats

- src/clients/Deluge.ts
- src/clients/QBittorrent.ts
- src/clients/RTorrent.ts
- src/clients/TorrentClient.ts
- src/clients/Transmission.ts
- src/inject.ts
- src/pushNotifier.ts
- src/utils.ts
This brings `ignoreNonRelevantFilesToResume` inline with `autoResumeMaxDownload` with preventing resuming if a non partial match or user doesn't not have partial matchMode.
> fix(inject/resume): only resume if partial match

- src/jobs.ts
This should reduce the `TypeError: terminated` errors.
> update(jobs): prevent certain jobs from running simultaneously

- src/action.ts
- src/clients/QBittorrent.ts
- src/jobs.ts
- src/searchee.ts
The file tree paths should always be relative to save path per the spec and is necessary for `cross-seed` to function.
> fix(action/linking): require absolute file tree paths

- src/arr.ts
- src/pipeline.ts
- src/torznab.ts
This better supports #947.
Also adding more detail to torznab failures. This should reduce some support tickets.
> update(search/delay): remove delay between cached searches

- src/db.ts
- src/torrent.ts
Expands on #986 to prevent retrying snatches if a tracker has failed too many times recently, on top of just a link. A snatch is always attempted at least once regardless of previous failures.
Also made the reverse lookup levenshtein fuzzy more conservative by basing on the length of the shortest title, instead of average.
> enhancement(snatch): temporarily store failed history for tracker

- src/action.ts
- src/clients/QBittorrent.ts
- src/inject.ts
This check is unnecessary for the inject job and can significantly slow down the process since each candidate can have 10+ searchees to try with.
Also now explicitly awaiting the long running promises created during the inject job as the change in startup/shutdown behavior no longer implicitly awaits for them. This only matters for `cross-seed inject`, not daemon mode.
> update(inject): don't refresh searchee for inject job

- src/pipeline.ts
A few other places are using the spread operator that could be problematic. But it's probably best to deal with it if it arises as it's clearly rare.
> fix(data): use concat to avoid overflows

- src/cmd.ts
- src/inject.ts
- src/pipeline.ts
- src/torrent.ts
This in support of this [FAQ](https://www.cross-seed.org/docs/basics/faq-troubleshooting#my-partial-matches-from-related-searches-are-missing-the-same-data-how-can-i-only-download-it-once) for rss/announce/inject. Since these process once candidate at a time, we can add the injected candidate for the searchee pool for the next candidate.
For search/webhook, this does not apply. Since these process one searchee at a time and all valid candidates are injected, there is no value to be derived unless the newly injected torrents recheck+complete in a couple seconds.
> enhancement(inject): add injected candidates to searchee pool

- src/pipeline.ts
- src/server.ts
- src/torrent.ts
Passes the cookie if autobrr supplies it: autobrr/autobrr#2107
To take advantage, users will need to update their payload but very few users will need to do this as these trackers are rare.
> enhancement(announce): support cookie

- package-lock.json
- src/action.ts
For `cross-seed inject`, we check every searchee against the .torrent file and run the action stage for all of them. This is because one searchee might have a file that another doesn't that the candidate needs. e.g:
* Candidate: mkv, srt, nfo
* SearcheeA: mkv, srt
* SearcheeB: mkv, nfo
The issue is that a single candidate can easily have 10+ valid searchees that the user already has. The slowdown happens when we are in the action stage for each injection, we call `client.inject()` which first checks if the torrent exists in client to return `ALREADY_EXISTS`. This API call can take a bit if the client has a large amount of torrents.
Instead, we already know if the candidate already exists in client as we need to use that save path if it does, rather than any from `linkDirs`. By removing …
> perf(inject): up to 16x speed up for job by reducing api calls

- README.md
This PR updates the README to have more flowing language, removes the reference to the "New breaking changes in v6" for a gentle mention of "if you're migrating", and removes autotorrent entirely - as we now support all of the clients AT2 supported, and it's of no benefit.
I also added a Repobeats graph at the bottom to gauge everyone's thoughts on the new look. You can see it at the link below.
https://github.com/cross-seed/cross-seed/tree/update-gh-readme
<hr>
Update our "description" to "Fully-automatic cross-seeding"
> update(gh/README) update and simplify README.md file on github

- src/pipeline.ts
- src/torrent.ts
This should help prevent lots of queries if lots of torrents are missing metadata or long time between indexing.
> perf(client): optimize client indexing

- src/constants.ts
- src/preFilter.ts
Titles such as `S01E02...` or `S03...` fails the episode and season regex since they do not start with a title. These fallback to the generic `VIDEO` mediaType since they usually have the right extensions.
These will no longer be searched, as we cannot properly determine the `mediaType`. There is also no reliable way to know what the title for these entries. Users can rename them in client if using `useClientTorrents: true` or rename the files if from `dataDirs` if they want to search these.
This only applies to `search` and `webhook`. `rss`, `announce`, and `inject` does not get filtered since they do not search.
> enhancement(preFilter): prevent searching for bad episode/season naming formats

- src/action.ts
- src/configSchema.ts
- src/constants.ts
- src/db.ts
- src/decide.ts
- src/inject.ts
- src/jobs.ts
- src/torrent.ts
This means when a user runs `cross-seed restore` after losing their torrent data, the injected torrents will be linked to `linkDir/Tracker` instead of `linkDir/UnknownTracker` for all.
The format is now the same as the one used for `outputDir` exception with `.cached`, `[mediaType][tracker]name[infoHash].cached.torrent`. The `.cached` is keep when copying to `outputDir` so they can still be distinguished from regular outputDir` entries.
This change is only future facing, it will not modify existing entries in the cache unless it's seen again. Instead, when a user runs `cross-seed restore`, it uses the updated format for the new entries and applies `[tracker]` to them when copying based on the tracker hosts in the .torrent files. So if the users has at least one of the new format for each …
> enhancement(torrent_cache): save entries with mediaType and tracker
